import db from "@/db/index";
import { regionTable } from "@/api/i18n/region/model";
import { SUPER_ADMIN_ID } from "./init";
import { sql } from "drizzle-orm";

export const initialRegionData = [
  {
    label_zhCN: "安道尔",
    label_enUS: "Andorra",
    alpha2Code: "AD",
    alpha3Code: "AND",
    numeric: 20,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "阿联酋",
    label_enUS: "United Arab Emirates",
    alpha2Code: "AE",
    alpha3Code: "ARE",
    numeric: 784,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "阿富汗",
    label_enUS: "Afghanistan",
    alpha2Code: "AF",
    alpha3Code: "AFG",
    numeric: 4,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "安提瓜和巴布达",
    label_enUS: "Antigua and Barbuda",
    alpha2Code: "AG",
    alpha3Code: "ATG",
    numeric: 28,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "安圭拉",
    label_enUS: "Anguilla",
    alpha2Code: "AI",
    alpha3Code: "AIA",
    numeric: 660,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "阿尔巴尼亚",
    label_enUS: "Albania",
    alpha2Code: "AL",
    alpha3Code: "ALB",
    numeric: 8,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "亚美尼亚",
    label_enUS: "Armenia",
    alpha2Code: "AM",
    alpha3Code: "ARM",
    numeric: 51,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "安哥拉",
    label_enUS: "Angola",
    alpha2Code: "AO",
    alpha3Code: "AGO",
    numeric: 24,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "南极洲",
    label_enUS: "Antarctica",
    alpha2Code: "AQ",
    alpha3Code: "ATA",
    numeric: 10,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "阿根廷",
    label_enUS: "Argentina",
    alpha2Code: "AR",
    alpha3Code: "ARG",
    numeric: 32,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "美属萨摩亚",
    label_enUS: "American Samoa",
    alpha2Code: "AS",
    alpha3Code: "ASM",
    numeric: 16,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "奥地利",
    label_enUS: "Austria",
    alpha2Code: "AT",
    alpha3Code: "AUT",
    numeric: 40,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "澳大利亚",
    label_enUS: "Australia",
    alpha2Code: "AU",
    alpha3Code: "AUS",
    numeric: 36,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "阿鲁巴",
    label_enUS: "Aruba",
    alpha2Code: "AW",
    alpha3Code: "ABW",
    numeric: 533,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "奥兰",
    label_enUS: "Åland Islands",
    alpha2Code: "AX",
    alpha3Code: "ALA",
    numeric: 248,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "阿塞拜疆",
    label_enUS: "Azerbaijan",
    alpha2Code: "AZ",
    alpha3Code: "AZE",
    numeric: 31,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "波黑",
    label_enUS: "Bosnia and Herzegovina",
    alpha2Code: "BA",
    alpha3Code: "BIH",
    numeric: 70,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴巴多斯",
    label_enUS: "Barbados",
    alpha2Code: "BB",
    alpha3Code: "BRB",
    numeric: 52,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "孟加拉国",
    label_enUS: "Bangladesh",
    alpha2Code: "BD",
    alpha3Code: "BGD",
    numeric: 50,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "比利时",
    label_enUS: "Belgium",
    alpha2Code: "BE",
    alpha3Code: "BEL",
    numeric: 56,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "布基纳法索",
    label_enUS: "Burkina Faso",
    alpha2Code: "BF",
    alpha3Code: "BFA",
    numeric: 854,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "保加利亚",
    label_enUS: "Bulgaria",
    alpha2Code: "BG",
    alpha3Code: "BGR",
    numeric: 100,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴林",
    label_enUS: "Bahrain",
    alpha2Code: "BH",
    alpha3Code: "BHR",
    numeric: 48,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "布隆迪",
    label_enUS: "Burundi",
    alpha2Code: "BI",
    alpha3Code: "BDI",
    numeric: 108,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "贝宁",
    label_enUS: "Benin",
    alpha2Code: "BJ",
    alpha3Code: "BEN",
    numeric: 204,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣巴泰勒米",
    label_enUS: "Saint Barthélemy",
    alpha2Code: "BL",
    alpha3Code: "BLM",
    numeric: 652,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "百慕大",
    label_enUS: "Bermuda",
    alpha2Code: "BM",
    alpha3Code: "BMU",
    numeric: 60,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "文莱",
    label_enUS: "Brunei Darussalam",
    alpha2Code: "BN",
    alpha3Code: "BRN",
    numeric: 96,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "玻利维亚",
    label_enUS: "Bolivia (Plurinational State of)",
    alpha2Code: "BO",
    alpha3Code: "BOL",
    numeric: 68,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "荷兰加勒比区",
    label_enUS: "Bonaire, Sint Eustatius and Saba",
    alpha2Code: "BQ",
    alpha3Code: "BES",
    numeric: 535,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "巴西",
    label_enUS: "Brazil",
    alpha2Code: "BR",
    alpha3Code: "BRA",
    numeric: 76,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴哈马",
    label_enUS: "Bahamas",
    alpha2Code: "BS",
    alpha3Code: "BHS",
    numeric: 44,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "不丹",
    label_enUS: "Bhutan",
    alpha2Code: "BT",
    alpha3Code: "BTN",
    numeric: 64,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "布韦岛",
    label_enUS: "Bouvet Island",
    alpha2Code: "BV",
    alpha3Code: "BVT",
    numeric: 74,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "博茨瓦纳",
    label_enUS: "Botswana",
    alpha2Code: "BW",
    alpha3Code: "BWA",
    numeric: 72,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "白俄罗斯",
    label_enUS: "Belarus",
    alpha2Code: "BY",
    alpha3Code: "BLR",
    numeric: 112,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "伯利兹",
    label_enUS: "Belize",
    alpha2Code: "BZ",
    alpha3Code: "BLZ",
    numeric: 84,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "加拿大",
    label_enUS: "Canada",
    alpha2Code: "CA",
    alpha3Code: "CAN",
    numeric: 124,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "科科斯（基林）群岛",
    label_enUS: "Cocos (Keeling) Islands",
    alpha2Code: "CC",
    alpha3Code: "CCK",
    numeric: 166,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "刚果民主共和国",
    label_enUS: "Congo (Democratic Republic of the)",
    alpha2Code: "CD",
    alpha3Code: "COD",
    numeric: 180,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "中非",
    label_enUS: "Central African Republic",
    alpha2Code: "CF",
    alpha3Code: "CAF",
    numeric: 140,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "刚果共和国",
    label_enUS: "Congo",
    alpha2Code: "CG",
    alpha3Code: "COG",
    numeric: 178,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瑞士",
    label_enUS: "Switzerland",
    alpha2Code: "CH",
    alpha3Code: "CHE",
    numeric: 756,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "科特迪瓦",
    label_enUS: "Côte d'Ivoire",
    alpha2Code: "CI",
    alpha3Code: "CIV",
    numeric: 384,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "库克群岛",
    label_enUS: "Cook Islands",
    alpha2Code: "CK",
    alpha3Code: "COK",
    numeric: 184,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "智利",
    label_enUS: "Chile",
    alpha2Code: "CL",
    alpha3Code: "CHL",
    numeric: 152,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "喀麦隆",
    label_enUS: "Cameroon",
    alpha2Code: "CM",
    alpha3Code: "CMR",
    numeric: 120,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "中国",
    label_enUS: "China",
    alpha2Code: "CN",
    alpha3Code: "CHN",
    numeric: 156,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "哥伦比亚",
    label_enUS: "Colombia",
    alpha2Code: "CO",
    alpha3Code: "COL",
    numeric: 170,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "哥斯达黎加",
    label_enUS: "Costa Rica",
    alpha2Code: "CR",
    alpha3Code: "CRI",
    numeric: 188,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "古巴",
    label_enUS: "Cuba",
    alpha2Code: "CU",
    alpha3Code: "CUB",
    numeric: 192,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "佛得角",
    label_enUS: "Cabo Verde",
    alpha2Code: "CV",
    alpha3Code: "CPV",
    numeric: 132,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "库拉索",
    label_enUS: "Curaçao",
    alpha2Code: "CW",
    alpha3Code: "CUW",
    numeric: 531,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "圣诞岛",
    label_enUS: "Christmas Island",
    alpha2Code: "CX",
    alpha3Code: "CXR",
    numeric: 162,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "塞浦路斯",
    label_enUS: "Cyprus",
    alpha2Code: "CY",
    alpha3Code: "CYP",
    numeric: 196,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "捷克",
    label_enUS: "Czechia",
    alpha2Code: "CZ",
    alpha3Code: "CZE",
    numeric: 203,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "德国",
    label_enUS: "Germany",
    alpha2Code: "DE",
    alpha3Code: "DEU",
    numeric: 276,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "吉布提",
    label_enUS: "Djibouti",
    alpha2Code: "DJ",
    alpha3Code: "DJI",
    numeric: 262,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "丹麦",
    label_enUS: "Denmark",
    alpha2Code: "DK",
    alpha3Code: "DNK",
    numeric: 208,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "多米尼克",
    label_enUS: "Dominica",
    alpha2Code: "DM",
    alpha3Code: "DMA",
    numeric: 212,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "多米尼加",
    label_enUS: "Dominican Republic",
    alpha2Code: "DO",
    alpha3Code: "DOM",
    numeric: 214,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "阿尔及利亚",
    label_enUS: "Algeria",
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    numeric: 12,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "厄瓜多尔",
    label_enUS: "Ecuador",
    alpha2Code: "EC",
    alpha3Code: "ECU",
    numeric: 218,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "爱沙尼亚",
    label_enUS: "Estonia",
    alpha2Code: "EE",
    alpha3Code: "EST",
    numeric: 233,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "埃及",
    label_enUS: "Egypt",
    alpha2Code: "EG",
    alpha3Code: "EGY",
    numeric: 818,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "西撒哈拉",
    label_enUS: "Western Sahara",
    alpha2Code: "EH",
    alpha3Code: "ESH",
    numeric: 732,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "厄立特里亚",
    label_enUS: "Eritrea",
    alpha2Code: "ER",
    alpha3Code: "ERI",
    numeric: 232,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "西班牙",
    label_enUS: "Spain",
    alpha2Code: "ES",
    alpha3Code: "ESP",
    numeric: 724,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "埃塞俄比亚",
    label_enUS: "Ethiopia",
    alpha2Code: "ET",
    alpha3Code: "ETH",
    numeric: 231,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "芬兰",
    label_enUS: "Finland",
    alpha2Code: "FI",
    alpha3Code: "FIN",
    numeric: 246,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "斐济",
    label_enUS: "Fiji",
    alpha2Code: "FJ",
    alpha3Code: "FJI",
    numeric: 242,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "福克兰群岛",
    label_enUS: "Falkland Islands (Malvinas)",
    alpha2Code: "FK",
    alpha3Code: "FLK",
    numeric: 238,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "密克罗尼西亚联邦",
    label_enUS: "Micronesia (Federated States of)",
    alpha2Code: "FM",
    alpha3Code: "FSM",
    numeric: 583,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "法罗群岛",
    label_enUS: "Faroe Islands",
    alpha2Code: "FO",
    alpha3Code: "FRO",
    numeric: 234,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "法国",
    label_enUS: "France",
    alpha2Code: "FR",
    alpha3Code: "FRA",
    numeric: 250,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "加蓬",
    label_enUS: "Gabon",
    alpha2Code: "GA",
    alpha3Code: "GAB",
    numeric: 266,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "英国",
    label_enUS: "United Kingdom of Great Britain and Northern Ireland",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    numeric: 826,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "格林纳达",
    label_enUS: "Grenada",
    alpha2Code: "GD",
    alpha3Code: "GRD",
    numeric: 308,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "格鲁吉亚",
    label_enUS: "Georgia",
    alpha2Code: "GE",
    alpha3Code: "GEO",
    numeric: 268,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "法属圭亚那",
    label_enUS: "French Guiana",
    alpha2Code: "GF",
    alpha3Code: "GUF",
    numeric: 254,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "根西",
    label_enUS: "Guernsey",
    alpha2Code: "GG",
    alpha3Code: "GGY",
    numeric: 831,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "加纳",
    label_enUS: "Ghana",
    alpha2Code: "GH",
    alpha3Code: "GHA",
    numeric: 288,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "直布罗陀",
    label_enUS: "Gibraltar",
    alpha2Code: "GI",
    alpha3Code: "GIB",
    numeric: 292,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "格陵兰",
    label_enUS: "Greenland",
    alpha2Code: "GL",
    alpha3Code: "GRL",
    numeric: 304,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "冈比亚",
    label_enUS: "Gambia",
    alpha2Code: "GM",
    alpha3Code: "GMB",
    numeric: 270,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "几内亚",
    label_enUS: "Guinea",
    alpha2Code: "GN",
    alpha3Code: "GIN",
    numeric: 324,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瓜德罗普",
    label_enUS: "Guadeloupe",
    alpha2Code: "GP",
    alpha3Code: "GLP",
    numeric: 312,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "赤道几内亚",
    label_enUS: "Equatorial Guinea",
    alpha2Code: "GQ",
    alpha3Code: "GNQ",
    numeric: 226,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "希腊",
    label_enUS: "Greece",
    alpha2Code: "GR",
    alpha3Code: "GRC",
    numeric: 300,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "南乔治亚和南桑威奇群岛",
    label_enUS: "South Georgia and the South Sandwich Islands",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    numeric: 239,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "危地马拉",
    label_enUS: "Guatemala",
    alpha2Code: "GT",
    alpha3Code: "GTM",
    numeric: 320,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "关岛",
    label_enUS: "Guam",
    alpha2Code: "GU",
    alpha3Code: "GUM",
    numeric: 316,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "几内亚比绍",
    label_enUS: "Guinea-Bissau",
    alpha2Code: "GW",
    alpha3Code: "GNB",
    numeric: 624,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圭亚那",
    label_enUS: "Guyana",
    alpha2Code: "GY",
    alpha3Code: "GUY",
    numeric: 328,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "香港",
    label_enUS: "Hong Kong",
    alpha2Code: "HK",
    alpha3Code: "HKG",
    numeric: 344,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "赫德岛和麦克唐纳群岛",
    label_enUS: "Heard Island and McDonald Islands",
    alpha2Code: "HM",
    alpha3Code: "HMD",
    numeric: 334,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "洪都拉斯",
    label_enUS: "Honduras",
    alpha2Code: "HN",
    alpha3Code: "HND",
    numeric: 340,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "克罗地亚",
    label_enUS: "Croatia",
    alpha2Code: "HR",
    alpha3Code: "HRV",
    numeric: 191,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "海地",
    label_enUS: "Haiti",
    alpha2Code: "HT",
    alpha3Code: "HTI",
    numeric: 332,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "匈牙利",
    label_enUS: "Hungary",
    alpha2Code: "HU",
    alpha3Code: "HUN",
    numeric: 348,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "印度尼西亚",
    label_enUS: "Indonesia",
    alpha2Code: "ID",
    alpha3Code: "IDN",
    numeric: 360,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "爱尔兰",
    label_enUS: "Ireland",
    alpha2Code: "IE",
    alpha3Code: "IRL",
    numeric: 372,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "以色列",
    label_enUS: "Israel",
    alpha2Code: "IL",
    alpha3Code: "ISR",
    numeric: 376,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马恩岛",
    label_enUS: "Isle of Man",
    alpha2Code: "IM",
    alpha3Code: "IMN",
    numeric: 833,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "印度",
    label_enUS: "India",
    alpha2Code: "IN",
    alpha3Code: "IND",
    numeric: 356,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "英属印度洋领地",
    label_enUS: "British Indian Ocean Territory",
    alpha2Code: "IO",
    alpha3Code: "IOT",
    numeric: 86,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "伊拉克",
    label_enUS: "Iraq",
    alpha2Code: "IQ",
    alpha3Code: "IRQ",
    numeric: 368,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "伊朗",
    label_enUS: "Iran (Islamic Republic of)",
    alpha2Code: "IR",
    alpha3Code: "IRN",
    numeric: 364,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "冰岛",
    label_enUS: "Iceland",
    alpha2Code: "IS",
    alpha3Code: "ISL",
    numeric: 352,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "意大利",
    label_enUS: "Italy",
    alpha2Code: "IT",
    alpha3Code: "ITA",
    numeric: 380,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "泽西",
    label_enUS: "Jersey",
    alpha2Code: "JE",
    alpha3Code: "JEY",
    numeric: 832,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "牙买加",
    label_enUS: "Jamaica",
    alpha2Code: "JM",
    alpha3Code: "JAM",
    numeric: 388,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "约旦",
    label_enUS: "Jordan",
    alpha2Code: "JO",
    alpha3Code: "JOR",
    numeric: 400,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "日本",
    label_enUS: "Japan",
    alpha2Code: "JP",
    alpha3Code: "JPN",
    numeric: 392,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "肯尼亚",
    label_enUS: "Kenya",
    alpha2Code: "KE",
    alpha3Code: "KEN",
    numeric: 404,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "吉尔吉斯斯坦",
    label_enUS: "Kyrgyzstan",
    alpha2Code: "KG",
    alpha3Code: "KGZ",
    numeric: 417,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "柬埔寨",
    label_enUS: "Cambodia",
    alpha2Code: "KH",
    alpha3Code: "KHM",
    numeric: 116,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "基里巴斯",
    label_enUS: "Kiribati",
    alpha2Code: "KI",
    alpha3Code: "KIR",
    numeric: 296,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "科摩罗",
    label_enUS: "Comoros",
    alpha2Code: "KM",
    alpha3Code: "COM",
    numeric: 174,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣基茨和尼维斯",
    label_enUS: "Saint Kitts and Nevis",
    alpha2Code: "KN",
    alpha3Code: "KNA",
    numeric: 659,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "朝鲜",
    label_enUS: "Korea (Democratic People's Republic of)",
    alpha2Code: "KP",
    alpha3Code: "PRK",
    numeric: 408,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "韩国",
    label_enUS: "Korea (Republic of)",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    numeric: 410,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "科威特",
    label_enUS: "Kuwait",
    alpha2Code: "KW",
    alpha3Code: "KWT",
    numeric: 414,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "开曼群岛",
    label_enUS: "Cayman Islands",
    alpha2Code: "KY",
    alpha3Code: "CYM",
    numeric: 136,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "哈萨克斯坦",
    label_enUS: "Kazakhstan",
    alpha2Code: "KZ",
    alpha3Code: "KAZ",
    numeric: 398,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "老挝",
    label_enUS: "Lao People's Democratic Republic",
    alpha2Code: "LA",
    alpha3Code: "LAO",
    numeric: 418,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "黎巴嫩",
    label_enUS: "Lebanon",
    alpha2Code: "LB",
    alpha3Code: "LBN",
    numeric: 422,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣卢西亚",
    label_enUS: "Saint Lucia",
    alpha2Code: "LC",
    alpha3Code: "LCA",
    numeric: 662,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "列支敦士登",
    label_enUS: "Liechtenstein",
    alpha2Code: "LI",
    alpha3Code: "LIE",
    numeric: 438,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "斯里兰卡",
    label_enUS: "Sri Lanka",
    alpha2Code: "LK",
    alpha3Code: "LKA",
    numeric: 144,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "利比里亚",
    label_enUS: "Liberia",
    alpha2Code: "LR",
    alpha3Code: "LBR",
    numeric: 430,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "莱索托",
    label_enUS: "Lesotho",
    alpha2Code: "LS",
    alpha3Code: "LSO",
    numeric: 426,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "立陶宛",
    label_enUS: "Lithuania",
    alpha2Code: "LT",
    alpha3Code: "LTU",
    numeric: 440,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "卢森堡",
    label_enUS: "Luxembourg",
    alpha2Code: "LU",
    alpha3Code: "LUX",
    numeric: 442,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "拉脱维亚",
    label_enUS: "Latvia",
    alpha2Code: "LV",
    alpha3Code: "LVA",
    numeric: 428,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "利比亚",
    label_enUS: "Libya",
    alpha2Code: "LY",
    alpha3Code: "LBY",
    numeric: 434,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "摩洛哥",
    label_enUS: "Morocco",
    alpha2Code: "MA",
    alpha3Code: "MAR",
    numeric: 504,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "摩纳哥",
    label_enUS: "Monaco",
    alpha2Code: "MC",
    alpha3Code: "MCO",
    numeric: 492,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "摩尔多瓦",
    label_enUS: "Moldova (Republic of)",
    alpha2Code: "MD",
    alpha3Code: "MDA",
    numeric: 498,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "黑山",
    label_enUS: "Montenegro",
    alpha2Code: "ME",
    alpha3Code: "MNE",
    numeric: 499,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "法属圣马丁",
    label_enUS: "Saint Martin (French part)",
    alpha2Code: "MF",
    alpha3Code: "MAF",
    numeric: 663,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "马达加斯加",
    label_enUS: "Madagascar",
    alpha2Code: "MG",
    alpha3Code: "MDG",
    numeric: 450,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马绍尔群岛",
    label_enUS: "Marshall Islands",
    alpha2Code: "MH",
    alpha3Code: "MHL",
    numeric: 584,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "北马其顿",
    label_enUS: "North Macedonia",
    alpha2Code: "MK",
    alpha3Code: "MKD",
    numeric: 807,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马里",
    label_enUS: "Mali",
    alpha2Code: "ML",
    alpha3Code: "MLI",
    numeric: 466,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "缅甸",
    label_enUS: "Myanmar",
    alpha2Code: "MM",
    alpha3Code: "MMR",
    numeric: 104,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "蒙古国",
    label_enUS: "Mongolia",
    alpha2Code: "MN",
    alpha3Code: "MNG",
    numeric: 496,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "澳门",
    label_enUS: "Macao",
    alpha2Code: "MO",
    alpha3Code: "MAC",
    numeric: 446,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "北马里亚纳群岛",
    label_enUS: "Northern Mariana Islands",
    alpha2Code: "MP",
    alpha3Code: "MNP",
    numeric: 580,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "马提尼克",
    label_enUS: "Martinique",
    alpha2Code: "MQ",
    alpha3Code: "MTQ",
    numeric: 474,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "毛里塔尼亚",
    label_enUS: "Mauritania",
    alpha2Code: "MR",
    alpha3Code: "MRT",
    numeric: 478,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "蒙特塞拉特",
    label_enUS: "Montserrat",
    alpha2Code: "MS",
    alpha3Code: "MSR",
    numeric: 500,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "马耳他",
    label_enUS: "Malta",
    alpha2Code: "MT",
    alpha3Code: "MLT",
    numeric: 470,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "毛里求斯",
    label_enUS: "Mauritius",
    alpha2Code: "MU",
    alpha3Code: "MUS",
    numeric: 480,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马尔代夫",
    label_enUS: "Maldives",
    alpha2Code: "MV",
    alpha3Code: "MDV",
    numeric: 462,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马拉维",
    label_enUS: "Malawi",
    alpha2Code: "MW",
    alpha3Code: "MWI",
    numeric: 454,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "墨西哥",
    label_enUS: "Mexico",
    alpha2Code: "MX",
    alpha3Code: "MEX",
    numeric: 484,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马来西亚",
    label_enUS: "Malaysia",
    alpha2Code: "MY",
    alpha3Code: "MYS",
    numeric: 458,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "莫桑比克",
    label_enUS: "Mozambique",
    alpha2Code: "MZ",
    alpha3Code: "MOZ",
    numeric: 508,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "纳米比亚",
    label_enUS: "Namibia",
    alpha2Code: "NA",
    alpha3Code: "NAM",
    numeric: 516,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "新喀里多尼亚",
    label_enUS: "New Caledonia",
    alpha2Code: "NC",
    alpha3Code: "NCL",
    numeric: 540,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "尼日尔",
    label_enUS: "Niger",
    alpha2Code: "NE",
    alpha3Code: "NER",
    numeric: 562,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "诺福克岛",
    label_enUS: "Norfolk Island",
    alpha2Code: "NF",
    alpha3Code: "NFK",
    numeric: 574,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "尼日利亚",
    label_enUS: "Nigeria",
    alpha2Code: "NG",
    alpha3Code: "NGA",
    numeric: 566,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "尼加拉瓜",
    label_enUS: "Nicaragua",
    alpha2Code: "NI",
    alpha3Code: "NIC",
    numeric: 558,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "荷兰",
    label_enUS: "Netherlands",
    alpha2Code: "NL",
    alpha3Code: "NLD",
    numeric: 528,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "挪威",
    label_enUS: "Norway",
    alpha2Code: "NO",
    alpha3Code: "NOR",
    numeric: 578,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "尼泊尔",
    label_enUS: "Nepal",
    alpha2Code: "NP",
    alpha3Code: "NPL",
    numeric: 524,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瑙鲁",
    label_enUS: "Nauru",
    alpha2Code: "NR",
    alpha3Code: "NRU",
    numeric: 520,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "纽埃",
    label_enUS: "Niue",
    alpha2Code: "NU",
    alpha3Code: "NIU",
    numeric: 570,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "新西兰",
    label_enUS: "New Zealand",
    alpha2Code: "NZ",
    alpha3Code: "NZL",
    numeric: 554,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "阿曼",
    label_enUS: "Oman",
    alpha2Code: "OM",
    alpha3Code: "OMN",
    numeric: 512,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴拿马",
    label_enUS: "Panama",
    alpha2Code: "PA",
    alpha3Code: "PAN",
    numeric: 591,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "秘鲁",
    label_enUS: "Peru",
    alpha2Code: "PE",
    alpha3Code: "PER",
    numeric: 604,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "法属波利尼西亚",
    label_enUS: "French Polynesia",
    alpha2Code: "PF",
    alpha3Code: "PYF",
    numeric: 258,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "巴布亚新几内亚",
    label_enUS: "Papua New Guinea",
    alpha2Code: "PG",
    alpha3Code: "PNG",
    numeric: 598,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "菲律宾",
    label_enUS: "Philippines",
    alpha2Code: "PH",
    alpha3Code: "PHL",
    numeric: 608,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴基斯坦",
    label_enUS: "Pakistan",
    alpha2Code: "PK",
    alpha3Code: "PAK",
    numeric: 586,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "波兰",
    label_enUS: "Poland",
    alpha2Code: "PL",
    alpha3Code: "POL",
    numeric: 616,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣皮埃尔和密克隆",
    label_enUS: "Saint Pierre and Miquelon",
    alpha2Code: "PM",
    alpha3Code: "SPM",
    numeric: 666,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "皮特凯恩群岛",
    label_enUS: "Pitcairn",
    alpha2Code: "PN",
    alpha3Code: "PCN",
    numeric: 612,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "波多黎各",
    label_enUS: "Puerto Rico",
    alpha2Code: "PR",
    alpha3Code: "PRI",
    numeric: 630,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "巴勒斯坦",
    label_enUS: "Palestine, State of",
    alpha2Code: "PS",
    alpha3Code: "PSE",
    numeric: 275,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "葡萄牙",
    label_enUS: "Portugal",
    alpha2Code: "PT",
    alpha3Code: "PRT",
    numeric: 620,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "帕劳",
    label_enUS: "Palau",
    alpha2Code: "PW",
    alpha3Code: "PLW",
    numeric: 585,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "巴拉圭",
    label_enUS: "Paraguay",
    alpha2Code: "PY",
    alpha3Code: "PRY",
    numeric: 600,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "卡塔尔",
    label_enUS: "Qatar",
    alpha2Code: "QA",
    alpha3Code: "QAT",
    numeric: 634,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "留尼汪",
    label_enUS: "Réunion",
    alpha2Code: "RE",
    alpha3Code: "REU",
    numeric: 638,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "罗马尼亚",
    label_enUS: "Romania",
    alpha2Code: "RO",
    alpha3Code: "ROU",
    numeric: 642,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "塞尔维亚",
    label_enUS: "Serbia",
    alpha2Code: "RS",
    alpha3Code: "SRB",
    numeric: 688,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "俄罗斯",
    label_enUS: "Russian Federation",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    numeric: 643,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "卢旺达",
    label_enUS: "Rwanda",
    alpha2Code: "RW",
    alpha3Code: "RWA",
    numeric: 646,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "沙特阿拉伯",
    label_enUS: "Saudi Arabia",
    alpha2Code: "SA",
    alpha3Code: "SAU",
    numeric: 682,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "所罗门群岛",
    label_enUS: "Solomon Islands",
    alpha2Code: "SB",
    alpha3Code: "SLB",
    numeric: 90,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "塞舌尔",
    label_enUS: "Seychelles",
    alpha2Code: "SC",
    alpha3Code: "SYC",
    numeric: 690,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "苏丹",
    label_enUS: "Sudan",
    alpha2Code: "SD",
    alpha3Code: "SDN",
    numeric: 729,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瑞典",
    label_enUS: "Sweden",
    alpha2Code: "SE",
    alpha3Code: "SWE",
    numeric: 752,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "新加坡",
    label_enUS: "Singapore",
    alpha2Code: "SG",
    alpha3Code: "SGP",
    numeric: 702,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣赫勒拿、阿森松和特里斯坦-达库尼亚",
    label_enUS: "Saint Helena, Ascension and Tristan da Cunha",
    alpha2Code: "SH",
    alpha3Code: "SHN",
    numeric: 654,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "斯洛文尼亚",
    label_enUS: "Slovenia",
    alpha2Code: "SI",
    alpha3Code: "SVN",
    numeric: 705,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "斯瓦尔巴和扬马延",
    label_enUS: "Svalbard and Jan Mayen",
    alpha2Code: "SJ",
    alpha3Code: "SJM",
    numeric: 744,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "斯洛伐克",
    label_enUS: "Slovakia",
    alpha2Code: "SK",
    alpha3Code: "SVK",
    numeric: 703,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "塞拉利昂",
    label_enUS: "Sierra Leone",
    alpha2Code: "SL",
    alpha3Code: "SLE",
    numeric: 694,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣马力诺",
    label_enUS: "San Marino",
    alpha2Code: "SM",
    alpha3Code: "SMR",
    numeric: 674,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "塞内加尔",
    label_enUS: "Senegal",
    alpha2Code: "SN",
    alpha3Code: "SEN",
    numeric: 686,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "索马里",
    label_enUS: "Somalia",
    alpha2Code: "SO",
    alpha3Code: "SOM",
    numeric: 706,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "苏里南",
    label_enUS: "Suriname",
    alpha2Code: "SR",
    alpha3Code: "SUR",
    numeric: 740,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "南苏丹",
    label_enUS: "South Sudan",
    alpha2Code: "SS",
    alpha3Code: "SSD",
    numeric: 728,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣多美和普林西比",
    label_enUS: "Sao Tome and Principe",
    alpha2Code: "ST",
    alpha3Code: "STP",
    numeric: 678,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "萨尔瓦多",
    label_enUS: "El Salvador",
    alpha2Code: "SV",
    alpha3Code: "SLV",
    numeric: 222,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "荷属圣马丁",
    label_enUS: "Sint Maarten (Dutch part)",
    alpha2Code: "SX",
    alpha3Code: "SXM",
    numeric: 534,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "叙利亚",
    label_enUS: "Syrian Arab Republic",
    alpha2Code: "SY",
    alpha3Code: "SYR",
    numeric: 760,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "斯威士兰",
    label_enUS: "Eswatini",
    alpha2Code: "SZ",
    alpha3Code: "SWZ",
    numeric: 748,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "特克斯和凯科斯群岛",
    label_enUS: "Turks and Caicos Islands",
    alpha2Code: "TC",
    alpha3Code: "TCA",
    numeric: 796,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "乍得",
    label_enUS: "Chad",
    alpha2Code: "TD",
    alpha3Code: "TCD",
    numeric: 148,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "法属南部和南极领地",
    label_enUS: "French Southern Territories",
    alpha2Code: "TF",
    alpha3Code: "ATF",
    numeric: 260,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "多哥",
    label_enUS: "Togo",
    alpha2Code: "TG",
    alpha3Code: "TGO",
    numeric: 768,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "泰国",
    label_enUS: "Thailand",
    alpha2Code: "TH",
    alpha3Code: "THA",
    numeric: 764,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "塔吉克斯坦",
    label_enUS: "Tajikistan",
    alpha2Code: "TJ",
    alpha3Code: "TJK",
    numeric: 762,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "托克劳",
    label_enUS: "Tokelau",
    alpha2Code: "TK",
    alpha3Code: "TKL",
    numeric: 772,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "东帝汶",
    label_enUS: "Timor-Leste",
    alpha2Code: "TL",
    alpha3Code: "TLS",
    numeric: 626,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "土库曼斯坦",
    label_enUS: "Turkmenistan",
    alpha2Code: "TM",
    alpha3Code: "TKM",
    numeric: 795,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "突尼斯",
    label_enUS: "Tunisia",
    alpha2Code: "TN",
    alpha3Code: "TUN",
    numeric: 788,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "汤加",
    label_enUS: "Tonga",
    alpha2Code: "TO",
    alpha3Code: "TON",
    numeric: 776,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "土耳其",
    label_enUS: "Türkiye",
    alpha2Code: "TR",
    alpha3Code: "TUR",
    numeric: 792,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "特立尼达和多巴哥",
    label_enUS: "Trinidad and Tobago",
    alpha2Code: "TT",
    alpha3Code: "TTO",
    numeric: 780,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "图瓦卢",
    label_enUS: "Tuvalu",
    alpha2Code: "TV",
    alpha3Code: "TUV",
    numeric: 798,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "中国台湾省",
    label_enUS: "Taiwan, Province of China",
    alpha2Code: "TW",
    alpha3Code: "TWN",
    numeric: 158,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "坦桑尼亚",
    label_enUS: "Tanzania, United Republic of",
    alpha2Code: "TZ",
    alpha3Code: "TZA",
    numeric: 834,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "乌克兰",
    label_enUS: "Ukraine",
    alpha2Code: "UA",
    alpha3Code: "UKR",
    numeric: 804,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "乌干达",
    label_enUS: "Uganda",
    alpha2Code: "UG",
    alpha3Code: "UGA",
    numeric: 800,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "美国本土外小岛屿",
    label_enUS: "United States Minor Outlying Islands",
    alpha2Code: "UM",
    alpha3Code: "UMI",
    numeric: 581,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "美国",
    label_enUS: "United States of America",
    alpha2Code: "US",
    alpha3Code: "USA",
    numeric: 840,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "乌拉圭",
    label_enUS: "Uruguay",
    alpha2Code: "UY",
    alpha3Code: "URY",
    numeric: 858,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "乌兹别克斯坦",
    label_enUS: "Uzbekistan",
    alpha2Code: "UZ",
    alpha3Code: "UZB",
    numeric: 860,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "梵蒂冈",
    label_enUS: "Holy See",
    alpha2Code: "VA",
    alpha3Code: "VAT",
    numeric: 336,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "圣文森特和格林纳丁斯",
    label_enUS: "Saint Vincent and the Grenadines",
    alpha2Code: "VC",
    alpha3Code: "VCT",
    numeric: 670,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "委内瑞拉",
    label_enUS: "Venezuela (Bolivarian Republic of)",
    alpha2Code: "VE",
    alpha3Code: "VEN",
    numeric: 862,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "英属维尔京群岛",
    label_enUS: "Virgin Islands (British)",
    alpha2Code: "VG",
    alpha3Code: "VGB",
    numeric: 92,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "美属维尔京群岛",
    label_enUS: "Virgin Islands (U.S.)",
    alpha2Code: "VI",
    alpha3Code: "VIR",
    numeric: 850,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "越南",
    label_enUS: "Viet Nam",
    alpha2Code: "VN",
    alpha3Code: "VNM",
    numeric: 704,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瓦努阿图",
    label_enUS: "Vanuatu",
    alpha2Code: "VU",
    alpha3Code: "VUT",
    numeric: 548,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "瓦利斯和富图纳",
    label_enUS: "Wallis and Futuna",
    alpha2Code: "WF",
    alpha3Code: "WLF",
    numeric: 876,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "萨摩亚",
    label_enUS: "Samoa",
    alpha2Code: "WS",
    alpha3Code: "WSM",
    numeric: 882,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "也门",
    label_enUS: "Yemen",
    alpha2Code: "YE",
    alpha3Code: "YEM",
    numeric: 887,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "马约特",
    label_enUS: "Mayotte",
    alpha2Code: "YT",
    alpha3Code: "MYT",
    numeric: 175,
    ISO3166Independent: false,
  },
  {
    label_zhCN: "南非",
    label_enUS: "South Africa",
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    numeric: 710,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "赞比亚",
    label_enUS: "Zambia",
    alpha2Code: "ZM",
    alpha3Code: "ZMB",
    numeric: 894,
    ISO3166Independent: true,
  },
  {
    label_zhCN: "津巴布韦",
    label_enUS: "Zimbabwe",
    alpha2Code: "ZW",
    alpha3Code: "ZWE",
    numeric: 716,
    ISO3166Independent: true,
  },
];

/**
 * 初始化国家地区数据
 */
export async function initCountryRegion(options?: { reset?: boolean }) {
  const stats = {
    total: initialRegionData.length,
    created: 0,
    updated: 0,
    skipped: 0,
  };
  console.log("🌍 开始初始化国家地区数据...");
  try {
    if (options?.reset) {
      await db.delete(regionTable);
      console.log("🗑️  已重置国家地区数据表");
    }

    // 分批处理 (增加安全性，解决 SQL 变量限制)
    const BATCH_SIZE = 10;
    for (let i = 0; i < initialRegionData.length; i += BATCH_SIZE) {
      // console.log(`🌍 正在同步地区批次 ${Math.floor(i / BATCH_SIZE) + 1} / ${Math.ceil(initialRegionData.length / BATCH_SIZE)}...`);
      const batch = initialRegionData.slice(i, i + BATCH_SIZE);
      const mappedBatch = batch.map((item) => ({
        labels: { "zh-CN": item.label_zhCN, "en-US": item.label_enUS },
        alpha2Code: item.alpha2Code,
        alpha3Code: item.alpha3Code,
        numeric: item.numeric,
        iso3166Independent: item.ISO3166Independent,
        isEnabled: true,
        creatorId: SUPER_ADMIN_ID,
      }));

      await db
        .insert(regionTable)
        .values(mappedBatch)
        .onConflictDoUpdate({
          target: regionTable.numeric,
          set: {
            labels: sql`excluded.labels`,
            alpha2Code: sql`excluded.alpha2_code`,
            alpha3Code: sql`excluded.alpha3_code`,
            iso3166Independent: sql`excluded.iso_3166_independent`,
          },
        });

      stats.created += mappedBatch.length;
    }

    console.log(`🌍 国家地区数据初始化完成: ${stats.total} 条记录已同步`);
    return stats;
  } catch (error) {
    console.error("❌ 国家地区初始化失败:", error);
    throw error;
  }
}
