// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量

/** 系统管理 */
export const SYSTEM = {
  READ: 'system:read',
  /** 用户管理 */
  USER: {
    READ: 'system.user:read',
    ADD: 'system.user:add',
    EDIT: 'system.user:edit',
    DELETE: 'system.user:delete',
    EXPORT: 'system.user:export',
  },
  /** 角色管理 */
  ROLE: {
    READ: 'system.role:read',
    ADD: 'system.role:add',
    EDIT: 'system.role:edit',
    DELETE: 'system.role:delete',
  },
  /** 权限管理 */
  PERMISSION: {
    READ: 'system.permission:read',
    ADD: 'system.permission:add',
    EDIT: 'system.permission:edit',
    DELETE: 'system.permission:delete',
  },
  /** 部门管理 */
  DEPARTMENT: {
    READ: 'system.department:read',
    ADD: 'system.department:add',
    EDIT: 'system.department:edit',
    DELETE: 'system.department:delete',
  },
  /** 菜单管理 */
  MENU: {
    READ: 'system.menu:read',
    ADD: 'system.menu:add',
    EDIT: 'system.menu:edit',
    DELETE: 'system.menu:delete',
  },
  /** 角色权限管理 */
  ROLE_PERMISSION: {
    READ: 'system.role_permission:read',
    ADD: 'system.role_permission:add',
    EDIT: 'system.role_permission:edit',
    DELETE: 'system.role_permission:delete',
    BATCH_DELETE: 'system.role_permission:batch-delete',
  },
  /** 个人信息 */
  AUTH: {
    READ: 'system.auth:read',
    EDIT: 'system.auth:edit',
  },
  /** 动态表单配置 */
  SCHEMA_FORM: {
    READ: 'system.schema_form:read',
    ADD: 'system.schema_form:add',
    EDIT: 'system.schema_form:edit',
    DELETE: 'system.schema_form:delete',
  },
  /** 动态表单数据 */
  SCHEMA_FORM_DATA: {
    READ: 'system.schema_form_data:read',
    ADD: 'system.schema_form_data:add',
    EDIT: 'system.schema_form_data:edit',
    DELETE: 'system.schema_form_data:delete',
  },
} as const;

/** 邮件 */
export const MAIL = {
  READ: 'mail:read',
  /** 邮件账户 */
  ACCOUNT: {
    READ: 'mail.account:read',
    ADD: 'mail.account:add',
    EDIT: 'mail.account:edit',
    DELETE: 'mail.account:delete',
  },
  /** 邮件模板 */
  TEMPLATE: {
    READ: 'mail.template:read',
    ADD: 'mail.template:add',
    EDIT: 'mail.template:edit',
    DELETE: 'mail.template:delete',
  },
  /** 邮件日志 */
  LOG: {
    READ: 'mail.log:read',
    VIEW: 'mail.log:view',
  },
} as const;

/** 国际化 */
export const I18N = {
  READ: 'i18n:read',
  /** 语言管理 */
  LANGUAGE: {
    READ: 'i18n.language:read',
    ADD: 'i18n.language:add',
    EDIT: 'i18n.language:edit',
    DELETE: 'i18n.language:delete',
  },
  /** 地区管理 */
  REGION: {
    READ: 'i18n.region:read',
    ADD: 'i18n.region:add',
    EDIT: 'i18n.region:edit',
    DELETE: 'i18n.region:delete',
  },
  /** 翻译管理 */
  TRANSLATION: {
    READ: 'i18n.translation:read',
    ADD: 'i18n.translation:add',
    EDIT: 'i18n.translation:edit',
    DELETE: 'i18n.translation:delete',
  },
} as const;

/** 运维 */
export const MAINTENANCE = {
  READ: 'maintenance:read',
  /** 缓存管理 */
  CACHE: {
    READ: 'maintenance.cache:read',
    ADD: 'maintenance.cache:add',
    EDIT: 'maintenance.cache:edit',
    DELETE: 'maintenance.cache:delete',
    VIEW: 'maintenance.cache:view',
  },
  /** 登录日志 */
  AUDIT_LOGIN: {
    READ: 'maintenance.audit_login:read',
  },
  /** 定时任务管理 */
  CRON: {
    READ: 'maintenance.cron:read',
    ADD: 'maintenance.cron:add',
    EDIT: 'maintenance.cron:edit',
    DELETE: 'maintenance.cron:delete',
  },
  /** API 采集任务管理 */
  API_TASK: {
    READ: 'maintenance.api_task:read',
    ADD: 'maintenance.api_task:add',
    EDIT: 'maintenance.api_task:edit',
    DELETE: 'maintenance.api_task:delete',
  },
  /** API 文档管理 */
  API_DOCS: {
    READ: 'maintenance.api_docs:read',
    ADD: 'maintenance.api_docs:add',
    EDIT: 'maintenance.api_docs:edit',
    DELETE: 'maintenance.api_docs:delete',
  },
} as const;

/** 存储 */
export const OSS = {
  READ: 'oss:read',
  /** 存储配置 */
  CONFIG: {
    READ: 'oss.config:read',
    ADD: 'oss.config:add',
    EDIT: 'oss.config:edit',
    DELETE: 'oss.config:delete',
  },
  /** 文件管理 */
  FILE: {
    READ: 'oss.file:read',
    ADD: 'oss.file:add',
    EDIT: 'oss.file:edit',
    DELETE: 'oss.file:delete',
  },
} as const;

/** 企业 */
export const ENTERPRISE = {
  READ: 'enterprise:read',
  /** 考勤管理 */
  ATTENDANCE: {
    READ: 'enterprise.attendance:read',
    ADD: 'enterprise.attendance:add',
    EDIT: 'enterprise.attendance:edit',
    DELETE: 'enterprise.attendance:delete',
  },
} as const;

/** AI */
export const AI = {
  READ: 'ai:read',
  /** AI 配置 */
  CONFIG: {
    READ: 'ai.config:read',
    ADD: 'ai.config:add',
    EDIT: 'ai.config:edit',
    DELETE: 'ai.config:delete',
  },
  /** AI 对话 */
  CHAT: {
    READ: 'ai.chat:read',
  },
} as const;

/** Swarm 集群 */
export const SWARM = {
  READ: 'swarm:read',
  /** Swarm 集群 Docker 服务管理 */
  DOCKER: {
    READ: 'swarm.docker:read',
    ADD: 'swarm.docker:add',
    EDIT: 'swarm.docker:edit',
    DELETE: 'swarm.docker:delete',
  },
  /** Swarm Docker配置管理 */
  DOCKER_CONFIG: {
    READ: 'swarm.docker_config:read',
    ADD: 'swarm.docker_config:add',
    EDIT: 'swarm.docker_config:edit',
    DELETE: 'swarm.docker_config:delete',
  },
  /** Swarm 节点管理 */
  NODES: {
    READ: 'swarm.nodes:read',
  },
} as const;
