graph LR
  src_index_ts["src/index.ts"] --> src_server_index_ts["src/server/index.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_middleware_logger_index_ts["src/middleware/logger/index.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_middleware_errorHandler_index_ts["src/middleware/errorHandler/index.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_doc_docRegister_ts["src/doc/docRegister.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_middleware_cors_index_ts["src/middleware/cors/index.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_middleware_nodeServer_index_ts["src/middleware/nodeServer/index.ts"]
  src_server_index_ts["src/server/index.ts"] --> src_api_index_ts["src/api/index.ts"]
  src_api_index_ts["src/api/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_index_ts["src/api/index.ts"] --> src_api_subFolderBatchRegister_ts["src/api/subFolderBatchRegister.ts"]
  src_api_index_ts["src/api/index.ts"] -.->|dynamic| src_api_login_index_ts["src/api/login/index.ts"]
  src_api_index_ts["src/api/index.ts"] -.->|dynamic| src_api_mail_index_ts["src/api/mail/index.ts"]
  src_api_index_ts["src/api/index.ts"] -.->|dynamic| src_api_user_index_ts["src/api/user/index.ts"]
  src_api_index_ts["src/api/index.ts"] -.->|"subfolder-batch @/api/subFolderBatchRegister"| COMPUTED[Runtime Computed]
  src_api_subFolderBatchRegister_ts["src/api/subFolderBatchRegister.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_subFolderBatchRegister_ts["src/api/subFolderBatchRegister.ts"] -.->|"runtime pathToFileURL"| COMPUTED[Runtime Computed]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_api_login_common_ts["src/api/login/common.ts"]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_api_login_wechat_ts["src/api/login/wechat.ts"]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_api_login_verify_ts["src/api/login/verify.ts"]
  src_api_login_index_ts["src/api/login/index.ts"] --> src_api_login_refresh_ts["src/api/login/refresh.ts"]
  src_api_login_common_ts["src/api/login/common.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_login_common_ts["src/api/login/common.ts"] --> src_api_login_service_ts["src/api/login/service.ts"]
  src_api_login_service_ts["src/api/login/service.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_login_service_ts["src/api/login/service.ts"] --> src_utils_token_ts["src/utils/token.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_add_index_ts["src/api/user/add/index.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_delete_index_ts["src/api/user/delete/index.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_get_index_ts["src/api/user/get/index.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_list_index_ts["src/api/user/list/index.ts"]
  src_api_user_service_ts["src/api/user/service.ts"] --> src_api_user_update_index_ts["src/api/user/update/index.ts"]
  src_api_user_db_table_ts["src/api/user/db.table.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_user_add_index_ts["src/api/user/add/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_user_add_index_ts["src/api/user/add/index.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_user_add_index_ts["src/api/user/add/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_add_index_ts["src/api/user/add/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_delete_index_ts["src/api/user/delete/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_user_delete_index_ts["src/api/user/delete/index.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_user_delete_index_ts["src/api/user/delete/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_get_index_ts["src/api/user/get/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_user_get_index_ts["src/api/user/get/index.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_user_get_index_ts["src/api/user/get/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_list_index_ts["src/api/user/list/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_user_list_index_ts["src/api/user/list/index.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_user_list_index_ts["src/api/user/list/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_list_index_ts["src/api/user/list/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_update_index_ts["src/api/user/update/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_user_update_index_ts["src/api/user/update/index.ts"] --> src_api_user_service_ts["src/api/user/service.ts"]
  src_api_user_update_index_ts["src/api/user/update/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_user_update_index_ts["src/api/user/update/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]
  src_api_login_wechat_ts["src/api/login/wechat.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_login_wechat_ts["src/api/login/wechat.ts"] --> src_api_login_service_ts["src/api/login/service.ts"]
  src_api_login_verify_ts["src/api/login/verify.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_login_verify_ts["src/api/login/verify.ts"] --> src_api_login_service_ts["src/api/login/service.ts"]
  src_api_login_refresh_ts["src/api/login/refresh.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_login_refresh_ts["src/api/login/refresh.ts"] --> src_api_login_service_ts["src/api/login/service.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] --> src_api_subFolderBatchRegister_ts["src/api/subFolderBatchRegister.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] -.->|dynamic| src_api_mail_account_index_ts["src/api/mail/account/index.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] -.->|dynamic| src_api_mail_log_index_ts["src/api/mail/log/index.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] -.->|dynamic| src_api_mail_send_index_ts["src/api/mail/send/index.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] -.->|dynamic| src_api_mail_template_index_ts["src/api/mail/template/index.ts"]
  src_api_mail_index_ts["src/api/mail/index.ts"] -.->|"subfolder-batch @/api/subFolderBatchRegister"| COMPUTED[Runtime Computed]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_update_index_ts["src/api/mail/account/update/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_delete_index_ts["src/api/mail/account/delete/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_verify_index_ts["src/api/mail/account/verify/index.ts"]
  src_api_mail_account_index_ts["src/api/mail/account/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_add_index_ts["src/api/mail/account/add/index.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_delete_index_ts["src/api/mail/account/delete/index.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"]
  src_api_mail_account_service_ts["src/api/mail/account/service.ts"] --> src_api_mail_account_update_index_ts["src/api/mail/account/update/index.ts"]
  src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_account_delete_index_ts["src/api/mail/account/delete/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_account_delete_index_ts["src/api/mail/account/delete/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_delete_index_ts["src/api/mail/account/delete/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_list_index_ts["src/api/mail/account/list/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_update_index_ts["src/api/mail/account/update/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_account_update_index_ts["src/api/mail/account/update/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_update_index_ts["src/api/mail/account/update/index.ts"] --> src_api_mail_account_db_table_ts["src/api/mail/account/db.table.ts"]
  src_api_mail_account_verify_index_ts["src/api/mail/account/verify/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_account_verify_index_ts["src/api/mail/account/verify/index.ts"] --> src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"]
  src_api_mail_log_index_ts["src/api/mail/log/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_log_index_ts["src/api/mail/log/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_mail_log_index_ts["src/api/mail/log/index.ts"] --> src_api_mail_crudFactory_ts["src/api/mail/crudFactory.ts"]
  src_api_mail_log_index_ts["src/api/mail/log/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_index_ts["src/api/mail/log/index.ts"] --> src_api_mail_log_service_adapter_ts["src/api/mail/log/service.adapter.ts"]
  src_api_mail_crudFactory_ts["src/api/mail/crudFactory.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_log_service_adapter_ts["src/api/mail/log/service.adapter.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_add_index_ts["src/api/mail/log/add/index.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_delete_index_ts["src/api/mail/log/delete/index.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_get_index_ts["src/api/mail/log/get/index.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_list_index_ts["src/api/mail/log/list/index.ts"]
  src_api_mail_log_service_ts["src/api/mail/log/service.ts"] --> src_api_mail_log_update_index_ts["src/api/mail/log/update/index.ts"]
  src_api_mail_log_add_index_ts["src/api/mail/log/add/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_add_index_ts["src/api/mail/log/add/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_add_index_ts["src/api/mail/log/add/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_add_index_ts["src/api/mail/log/add/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_delete_index_ts["src/api/mail/log/delete/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_delete_index_ts["src/api/mail/log/delete/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_delete_index_ts["src/api/mail/log/delete/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_get_index_ts["src/api/mail/log/get/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_get_index_ts["src/api/mail/log/get/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_get_index_ts["src/api/mail/log/get/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_list_index_ts["src/api/mail/log/list/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_list_index_ts["src/api/mail/log/list/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_list_index_ts["src/api/mail/log/list/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_list_index_ts["src/api/mail/log/list/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_log_update_index_ts["src/api/mail/log/update/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_log_update_index_ts["src/api/mail/log/update/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_log_update_index_ts["src/api/mail/log/update/index.ts"] --> src_api_mail_log_db_table_ts["src/api/mail/log/db.table.ts"]
  src_api_mail_send_index_ts["src/api/mail/send/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_send_index_ts["src/api/mail/send/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_mail_send_index_ts["src/api/mail/send/index.ts"] --> src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"]
  src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"] --> src_api_mail_send_service_ts["src/api/mail/send/service.ts"]
  src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"] --> src_api_mail_account_service_ts["src/api/mail/account/service.ts"]
  src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"] --> src_api_mail_log_service_ts["src/api/mail/log/service.ts"]
  src_api_mail_send_service_ts["src/api/mail/send/service.ts"] --> src_api_mail_account_get_index_ts["src/api/mail/account/get/index.ts"]
  src_api_mail_send_service_ts["src/api/mail/send/service.ts"] --> src_api_mail_send_single_index_ts["src/api/mail/send/single/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_add_index_ts["src/api/mail/template/add/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_delete_index_ts["src/api/mail/template/delete/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_get_index_ts["src/api/mail/template/get/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_list_index_ts["src/api/mail/template/list/index.ts"]
  src_api_mail_template_service_ts["src/api/mail/template/service.ts"] --> src_api_mail_template_update_index_ts["src/api/mail/template/update/index.ts"]
  src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"] --> src_db_index_ts["src/db/index.ts"]
  src_api_mail_template_add_index_ts["src/api/mail/template/add/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_template_add_index_ts["src/api/mail/template/add/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_template_add_index_ts["src/api/mail/template/add/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_add_index_ts["src/api/mail/template/add/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_delete_index_ts["src/api/mail/template/delete/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_template_delete_index_ts["src/api/mail/template/delete/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_template_delete_index_ts["src/api/mail/template/delete/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_get_index_ts["src/api/mail/template/get/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_template_get_index_ts["src/api/mail/template/get/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_template_get_index_ts["src/api/mail/template/get/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_list_index_ts["src/api/mail/template/list/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_template_list_index_ts["src/api/mail/template/list/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_template_list_index_ts["src/api/mail/template/list/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_list_index_ts["src/api/mail/template/list/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_update_index_ts["src/api/mail/template/update/index.ts"] --> src_middleware_errorHandler_schema_ts["src/middleware/errorHandler/schema.ts"]
  src_api_mail_template_update_index_ts["src/api/mail/template/update/index.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_mail_template_update_index_ts["src/api/mail/template/update/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_index_ts["src/api/mail/template/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_mail_template_index_ts["src/api/mail/template/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_mail_template_index_ts["src/api/mail/template/index.ts"] --> src_api_mail_crudFactory_ts["src/api/mail/crudFactory.ts"]
  src_api_mail_template_index_ts["src/api/mail/template/index.ts"] --> src_api_mail_template_db_table_ts["src/api/mail/template/db.table.ts"]
  src_api_mail_template_index_ts["src/api/mail/template/index.ts"] --> src_api_mail_template_service_adapter_ts["src/api/mail/template/service.adapter.ts"]
  src_api_mail_template_service_adapter_ts["src/api/mail/template/service.adapter.ts"] --> src_api_mail_template_service_ts["src/api/mail/template/service.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_types_app_d_ts["src/types/app.d.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_pathRegister_ts["src/api/pathRegister.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_add_index_ts["src/api/user/add/index.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_get_index_ts["src/api/user/get/index.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_list_index_ts["src/api/user/list/index.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_update_index_ts["src/api/user/update/index.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_delete_index_ts["src/api/user/delete/index.ts"]
  src_api_user_index_ts["src/api/user/index.ts"] --> src_api_user_db_table_ts["src/api/user/db.table.ts"]

  classDef computed fill:#f96,stroke:#333,stroke-width:2px
  class COMPUTED computed
