CREATE TABLE `compliance_archives` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`source_system` text(100) DEFAULT 'self' NOT NULL,
	`source_database` text(100) DEFAULT 'self' NOT NULL,
	`source_table` text(100) NOT NULL,
	`source_primary_key` text(100) NOT NULL,
	`delete_reason` text(200),
	`delete_type` text(100),
	`record_snapshot` text,
	`remark` text(500),
	`restorable` integer NOT NULL,
	`restore_until_time_utc` integer,
	`restored_time_utc` integer,
	`restorer_id` integer,
	`compliance_note` text(500),
	`creator_id` integer NOT NULL,
	`updater_id` integer,
	`create_time_utc` integer DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000 + CAST(substr(strftime('%f', 'now'), 4, 3) AS INTEGER)) NOT NULL,
	`update_time_utc` integer
);
