// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量

/** 系统管理 */
export const infra_system = {
  read: 'infra.system:read',
  /** 用户管理 */
  user: {
    read: 'infra.system.user:read',
    add: 'infra.system.user:add',
    edit: 'infra.system.user:edit',
    delete: 'infra.system.user:delete',
    export: 'infra.system.user:export',
  },
  /** 角色管理 */
  role: {
    read: 'infra.system.role:read',
    add: 'infra.system.role:add',
    edit: 'infra.system.role:edit',
    delete: 'infra.system.role:delete',
  },
  /** 权限管理 */
  permission: {
    read: 'infra.system.permission:read',
    add: 'infra.system.permission:add',
    edit: 'infra.system.permission:edit',
    delete: 'infra.system.permission:delete',
  },
  /** 部门管理 */
  department: {
    read: 'infra.system.department:read',
    add: 'infra.system.department:add',
    edit: 'infra.system.department:edit',
    delete: 'infra.system.department:delete',
  },
  /** 菜单管理 */
  menu: {
    read: 'infra.system.menu:read',
    add: 'infra.system.menu:add',
    edit: 'infra.system.menu:edit',
    delete: 'infra.system.menu:delete',
  },
  /** 角色权限管理 */
  role_permission: {
    read: 'infra.system.role_permission:read',
    add: 'infra.system.role_permission:add',
    edit: 'infra.system.role_permission:edit',
    delete: 'infra.system.role_permission:delete',
    batch_delete: 'infra.system.role_permission:batch-delete',
  },
  /** 个人信息 */
  auth: {
    read: 'infra.system.auth:read',
    edit: 'infra.system.auth:edit',
  },
} as const;

/** 邮件 */
export const infra_mail = {
  read: 'infra.mail:read',
  /** 邮件账户 */
  account: {
    read: 'infra.mail.account:read',
    add: 'infra.mail.account:add',
    edit: 'infra.mail.account:edit',
    delete: 'infra.mail.account:delete',
  },
  /** 邮件模板 */
  template: {
    read: 'infra.mail.template:read',
    add: 'infra.mail.template:add',
    edit: 'infra.mail.template:edit',
    delete: 'infra.mail.template:delete',
  },
  /** 邮件日志 */
  log: {
    read: 'infra.mail.log:read',
    view: 'infra.mail.log:view',
  },
  /** 邮件操作 */
  action: {
    read: 'infra.mail.action:read',
    add: 'infra.mail.action:add',
  },
} as const;

/** 国际化 */
export const infra_i18n = {
  read: 'infra.i18n:read',
  /** 语言管理 */
  language: {
    read: 'infra.i18n.language:read',
    add: 'infra.i18n.language:add',
    edit: 'infra.i18n.language:edit',
    delete: 'infra.i18n.language:delete',
  },
  /** 地区管理 */
  region: {
    read: 'infra.i18n.region:read',
    add: 'infra.i18n.region:add',
    edit: 'infra.i18n.region:edit',
    delete: 'infra.i18n.region:delete',
  },
  /** 翻译管理 */
  translation: {
    read: 'infra.i18n.translation:read',
    add: 'infra.i18n.translation:add',
    edit: 'infra.i18n.translation:edit',
    delete: 'infra.i18n.translation:delete',
  },
} as const;

/** 运维 */
export const infra_maintenance = {
  read: 'infra.maintenance:read',
  /** 缓存管理 */
  cache: {
    read: 'infra.maintenance.cache:read',
    add: 'infra.maintenance.cache:add',
    edit: 'infra.maintenance.cache:edit',
    delete: 'infra.maintenance.cache:delete',
    view: 'infra.maintenance.cache:view',
  },
  /** 登录日志 */
  audit_login: {
    read: 'infra.maintenance.audit_login:read',
  },
  /** 定时任务管理 */
  cron: {
    read: 'infra.maintenance.cron:read',
    add: 'infra.maintenance.cron:add',
    edit: 'infra.maintenance.cron:edit',
    delete: 'infra.maintenance.cron:delete',
  },
  /** API 采集任务管理 */
  api_task: {
    read: 'infra.maintenance.api_task:read',
    add: 'infra.maintenance.api_task:add',
    edit: 'infra.maintenance.api_task:edit',
    delete: 'infra.maintenance.api_task:delete',
  },
  /** API 文档管理 */
  api_docs: {
    read: 'infra.maintenance.api_docs:read',
    add: 'infra.maintenance.api_docs:add',
    edit: 'infra.maintenance.api_docs:edit',
    delete: 'infra.maintenance.api_docs:delete',
  },
  /** 合规归档 */
  compliance: {
    read: 'infra.maintenance.compliance:read',
  },
  /** 初始化数据 */
  init: {
    read: 'infra.maintenance.init:read',
  },
} as const;

/** 基础设施 */
export const infra = {
  read: 'infra:read',
} as const;

/** 数据管理 */
export const infra_data = {
  read: 'infra.data:read',
  /** 动态表单配置 */
  schema_form: {
    read: 'infra.data.schema_form:read',
    add: 'infra.data.schema_form:add',
    edit: 'infra.data.schema_form:edit',
    delete: 'infra.data.schema_form:delete',
  },
  /** 动态表单数据 */
  schema_form_data: {
    read: 'infra.data.schema_form_data:read',
    add: 'infra.data.schema_form_data:add',
    edit: 'infra.data.schema_form_data:edit',
    delete: 'infra.data.schema_form_data:delete',
  },
  /** 对象存储 */
  oss: {
    read: 'infra.data.oss:read',
    /** 存储配置 */
    config: {
      read: 'infra.data.oss.config:read',
      add: 'infra.data.oss.config:add',
      edit: 'infra.data.oss.config:edit',
      delete: 'infra.data.oss.config:delete',
    },
    /** 文件管理 */
    file: {
      read: 'infra.data.oss.file:read',
      add: 'infra.data.oss.file:add',
      edit: 'infra.data.oss.file:edit',
      delete: 'infra.data.oss.file:delete',
    },
  },
} as const;

/** 企业管理 */
export const enterprise = {
  read: 'enterprise:read',
  /** 考勤管理 */
  attendance: {
    read: 'enterprise.attendance:read',
    add: 'enterprise.attendance:add',
    edit: 'enterprise.attendance:edit',
    delete: 'enterprise.attendance:delete',
  },
  /** 工作流编排 */
  workflow: {
    read: 'enterprise.workflow:read',
    add: 'enterprise.workflow:add',
    edit: 'enterprise.workflow:edit',
    delete: 'enterprise.workflow:delete',
  },
} as const;

/** AI */
export const infra_ai = {
  read: 'infra.ai:read',
  /** AI 配置 */
  config: {
    read: 'infra.ai.config:read',
    add: 'infra.ai.config:add',
    edit: 'infra.ai.config:edit',
    delete: 'infra.ai.config:delete',
  },
  /** AI 对话 */
  chat: {
    read: 'infra.ai.chat:read',
  },
} as const;

/** Swarm 集群 */
export const infra_swarm = {
  read: 'infra.swarm:read',
  /** Swarm 集群 Docker 服务管理 */
  docker: {
    read: 'infra.swarm.docker:read',
    add: 'infra.swarm.docker:add',
    edit: 'infra.swarm.docker:edit',
    delete: 'infra.swarm.docker:delete',
  },
  /** Swarm Docker配置管理 */
  docker_config: {
    read: 'infra.swarm.docker_config:read',
    add: 'infra.swarm.docker_config:add',
    edit: 'infra.swarm.docker_config:edit',
    delete: 'infra.swarm.docker_config:delete',
  },
  /** Swarm 节点管理 */
  nodes: {
    read: 'infra.swarm.nodes:read',
  },
} as const;

/** RPA */
export const infra_rpa = {
  read: 'infra.rpa:read',
  /** 浏览器配置 */
  browser: {
    read: 'infra.rpa.browser:read',
    add: 'infra.rpa.browser:add',
    edit: 'infra.rpa.browser:edit',
    delete: 'infra.rpa.browser:delete',
  },
} as const;

export const permissions = {
  infra: {
    ...infra,
    system: infra_system,
    mail: infra_mail,
    i18n: infra_i18n,
    maintenance: infra_maintenance,
    data: infra_data,
    ai: infra_ai,
    swarm: infra_swarm,
    rpa: infra_rpa,
  },
  enterprise: enterprise,
} as const;
