// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量

export const permissions = {
  admin: {
    /** 底座 */
    base: {
      read: 'admin.base:read',
      /** sys_config */
      sys_config: {
        read: 'admin.base.sys_config:read',
        add: 'admin.base.sys_config:add',
        edit: 'admin.base.sys_config:edit',
        delete: 'admin.base.sys_config:delete',
      },
      /** 日志 */
      log: {
        read: 'admin.base.log:read',
      },
    },
    /** 系统管理 */
    system: {
      read: 'admin.system:read',
      /** 用户管理 */
      user: {
        read: 'admin.system.user:read',
        add: 'admin.system.user:add',
        edit: 'admin.system.user:edit',
        delete: 'admin.system.user:delete',
        export: 'admin.system.user:export',
      },
      /** 角色管理 */
      role: {
        read: 'admin.system.role:read',
        add: 'admin.system.role:add',
        edit: 'admin.system.role:edit',
        delete: 'admin.system.role:delete',
      },
      /** 权限管理 */
      permission: {
        read: 'admin.system.permission:read',
        add: 'admin.system.permission:add',
        edit: 'admin.system.permission:edit',
        delete: 'admin.system.permission:delete',
      },
      /** 部门管理 */
      department: {
        read: 'admin.system.department:read',
        add: 'admin.system.department:add',
        edit: 'admin.system.department:edit',
        delete: 'admin.system.department:delete',
      },
      /** 菜单管理 */
      menu: {
        read: 'admin.system.menu:read',
        add: 'admin.system.menu:add',
        edit: 'admin.system.menu:edit',
        delete: 'admin.system.menu:delete',
      },
      /** 角色权限管理 */
      role_permission: {
        read: 'admin.system.role_permission:read',
        add: 'admin.system.role_permission:add',
        edit: 'admin.system.role_permission:edit',
        delete: 'admin.system.role_permission:delete',
        batch_delete: 'admin.system.role_permission:batch-delete',
      },
      /** 个人信息 */
      auth: {
        read: 'admin.system.auth:read',
        edit: 'admin.system.auth:edit',
      },
      /** API 令牌管理 */
      api_token: {
        read: 'admin.system.api_token:read',
        add: 'admin.system.api_token:add',
        edit: 'admin.system.api_token:edit',
        delete: 'admin.system.api_token:delete',
      },
    },
    /** 邮件 */
    mail: {
      read: 'admin.mail:read',
      add: 'admin.mail:add',
      edit: 'admin.mail:edit',
      delete: 'admin.mail:delete',
      /** 自动生成: recipient */
      recipient: {
        read: 'admin.mail.recipient:read',
        add: 'admin.mail.recipient:add',
        edit: 'admin.mail.recipient:edit',
        delete: 'admin.mail.recipient:delete',
      },
      /** 邮件账户 */
      account: {
        read: 'admin.mail.account:read',
        add: 'admin.mail.account:add',
        edit: 'admin.mail.account:edit',
        delete: 'admin.mail.account:delete',
      },
      /** 邮件模板 */
      template: {
        read: 'admin.mail.template:read',
        add: 'admin.mail.template:add',
        edit: 'admin.mail.template:edit',
        delete: 'admin.mail.template:delete',
      },
      /** 邮件日志 */
      log: {
        read: 'admin.mail.log:read',
        view: 'admin.mail.log:view',
      },
      /** 邮件操作 */
      action: {
        read: 'admin.mail.action:read',
        add: 'admin.mail.action:add',
      },
    },
    /** 国际化 */
    i18n: {
      read: 'admin.i18n:read',
      /** 语言管理 */
      language: {
        read: 'admin.i18n.language:read',
        add: 'admin.i18n.language:add',
        edit: 'admin.i18n.language:edit',
        delete: 'admin.i18n.language:delete',
      },
      /** 地区管理 */
      region: {
        read: 'admin.i18n.region:read',
        add: 'admin.i18n.region:add',
        edit: 'admin.i18n.region:edit',
        delete: 'admin.i18n.region:delete',
      },
      /** 翻译管理 */
      translation: {
        read: 'admin.i18n.translation:read',
        add: 'admin.i18n.translation:add',
        edit: 'admin.i18n.translation:edit',
        delete: 'admin.i18n.translation:delete',
      },
    },
    /** 运维 */
    maintenance: {
      read: 'admin.maintenance:read',
      /** 缓存管理 */
      cache: {
        read: 'admin.maintenance.cache:read',
        add: 'admin.maintenance.cache:add',
        edit: 'admin.maintenance.cache:edit',
        delete: 'admin.maintenance.cache:delete',
        view: 'admin.maintenance.cache:view',
      },
      /** 登录日志 */
      login_log: {
        read: 'admin.maintenance.login_log:read',
      },
      /** 定时任务管理 */
      cron: {
        read: 'admin.maintenance.cron:read',
        add: 'admin.maintenance.cron:add',
        edit: 'admin.maintenance.cron:edit',
        delete: 'admin.maintenance.cron:delete',
      },
      /** API 采集任务管理 */
      api_task: {
        read: 'admin.maintenance.api_task:read',
        add: 'admin.maintenance.api_task:add',
        edit: 'admin.maintenance.api_task:edit',
        delete: 'admin.maintenance.api_task:delete',
      },
      /** API 文档管理 */
      api_docs: {
        read: 'admin.maintenance.api_docs:read',
        add: 'admin.maintenance.api_docs:add',
        edit: 'admin.maintenance.api_docs:edit',
        delete: 'admin.maintenance.api_docs:delete',
      },
      /** 合规归档 */
      compliance: {
        read: 'admin.maintenance.compliance:read',
      },
      /** 初始化数据 */
      init: {
        read: 'admin.maintenance.init:read',
      },
    },
    read: 'admin:read',
    /** 数据库 */
    data: {
      read: 'admin.data:read',
      /** 动态表单 */
      schema_form: {
        read: 'admin.data.schema_form:read',
        add: 'admin.data.schema_form:add',
        edit: 'admin.data.schema_form:edit',
        delete: 'admin.data.schema_form:delete',
      },
      /** 表单数据 */
      schema_form_data: {
        read: 'admin.data.schema_form_data:read',
        add: 'admin.data.schema_form_data:add',
        edit: 'admin.data.schema_form_data:edit',
        delete: 'admin.data.schema_form_data:delete',
      },
    },
    /** 对象存储 */
    oss: {
      read: 'admin.oss:read',
      /** 存储配置 */
      config: {
        read: 'admin.oss.config:read',
        add: 'admin.oss.config:add',
        edit: 'admin.oss.config:edit',
        delete: 'admin.oss.config:delete',
      },
      /** 文件管理 */
      file: {
        read: 'admin.oss.file:read',
        add: 'admin.oss.file:add',
        edit: 'admin.oss.file:edit',
        delete: 'admin.oss.file:delete',
      },
    },
    /** AI */
    ai: {
      read: 'admin.ai:read',
      /** AI 配置 */
      config: {
        read: 'admin.ai.config:read',
        add: 'admin.ai.config:add',
        edit: 'admin.ai.config:edit',
        delete: 'admin.ai.config:delete',
      },
      /** AI 对话 */
      chat: {
        read: 'admin.ai.chat:read',
      },
      /** 全局 AI 搜索 */
      search: {
        read: 'admin.ai.search:read',
      },
      /** OpenAI 兼容服务 */
      openai: {
        read: 'admin.ai.openai:read',
      },
    },
    /** Swarm 集群 */
    swarm: {
      read: 'admin.swarm:read',
      /** Swarm 集群 Docker 服务管理 */
      docker: {
        read: 'admin.swarm.docker:read',
        add: 'admin.swarm.docker:add',
        edit: 'admin.swarm.docker:edit',
        delete: 'admin.swarm.docker:delete',
      },
      /** Swarm Docker配置管理 */
      docker_config: {
        read: 'admin.swarm.docker_config:read',
        add: 'admin.swarm.docker_config:add',
        edit: 'admin.swarm.docker_config:edit',
        delete: 'admin.swarm.docker_config:delete',
      },
      /** Swarm 节点管理 */
      nodes: {
        read: 'admin.swarm.nodes:read',
      },
    },
    /** RPA */
    rpa: {
      read: 'admin.rpa:read',
      /** RPA 配置 */
      config: {
        read: 'admin.rpa.config:read',
        add: 'admin.rpa.config:add',
        edit: 'admin.rpa.config:edit',
        delete: 'admin.rpa.config:delete',
      },
    },
    /** MQTT 消息管理 */
    mqtt: {
      read: 'admin.mqtt:read',
      /** MQTT 控制台 */
      console: {
        read: 'admin.mqtt.console:read',
        add: 'admin.mqtt.console:add',
        edit: 'admin.mqtt.console:edit',
        delete: 'admin.mqtt.console:delete',
      },
      /** MQTT 配置 */
      config: {
        read: 'admin.mqtt.config:read',
        add: 'admin.mqtt.config:add',
        edit: 'admin.mqtt.config:edit',
        delete: 'admin.mqtt.config:delete',
      },
    },
    /** 实时通话 */
    voice: {
      read: 'admin.voice:read',
      /** 通话会话 */
      session: {
        read: 'admin.voice.session:read',
        add: 'admin.voice.session:add',
        edit: 'admin.voice.session:edit',
      },
      /** 服务配置 */
      config: {
        read: 'admin.voice.config:read',
        add: 'admin.voice.config:add',
        edit: 'admin.voice.config:edit',
        delete: 'admin.voice.config:delete',
      },
    },
    /** 移动端管理 */
    mobile: {
      read: 'admin.mobile:read',
      /** device */
      device: {
        read: 'admin.mobile.device:read',
        add: 'admin.mobile.device:add',
        edit: 'admin.mobile.device:edit',
        delete: 'admin.mobile.device:delete',
        sync: 'admin.mobile.device:sync',
      },
      /** app */
      app: {
        read: 'admin.mobile.app:read',
        add: 'admin.mobile.app:add',
        edit: 'admin.mobile.app:edit',
        delete: 'admin.mobile.app:delete',
      },
      /** app_version */
      app_version: {
        read: 'admin.mobile.app_version:read',
        add: 'admin.mobile.app_version:add',
        edit: 'admin.mobile.app_version:edit',
        delete: 'admin.mobile.app_version:delete',
      },
      /** device_app */
      device_app: {
        read: 'admin.mobile.device_app:read',
        sync: 'admin.mobile.device_app:sync',
        install: 'admin.mobile.device_app:install',
      },
      /** async_task */
      async_task: {
        read: 'admin.mobile.async_task:read',
      },
    },
  },
  enterprise: {
    read: 'enterprise:read',
    /** enterprise.mail */
    mail: {
      read: 'enterprise.mail:read',
      /** edm */
      edm: {
        read: 'enterprise.mail.edm:read',
        add: 'enterprise.mail.edm:add',
        edit: 'enterprise.mail.edm:edit',
        delete: 'enterprise.mail.edm:delete',
      },
    },
    /** 组织管理 */
    organization: {
      read: 'organization:read',
      /** 考勤管理 */
      attendance: {
        read: 'organization.attendance:read',
        add: 'organization.attendance:add',
        edit: 'organization.attendance:edit',
        delete: 'organization.attendance:delete',
      },
    },
    /** 事务管理 */
    executive: {
      read: 'executive:read',
      /** 工作流编排 */
      workflow: {
        read: 'executive.workflow:read',
        add: 'executive.workflow:add',
        edit: 'executive.workflow:edit',
        delete: 'executive.workflow:delete',
      },
    },
  },
  personal: {
    read: 'personal:read',
    /** 账号配置 */
    base: {
      read: 'personal.base:read',
      /** preference */
      preference: {
        read: 'personal.base.preference:read',
        add: 'personal.base.preference:add',
        edit: 'personal.base.preference:edit',
        delete: 'personal.base.preference:delete',
      },
      /** user_config */
      user_config: {
        read: 'personal.base.user_config:read',
        add: 'personal.base.user_config:add',
        edit: 'personal.base.user_config:edit',
        delete: 'personal.base.user_config:delete',
      },
    },
    /** 健康与医疗 */
    health: {
      read: 'personal.health:read',
      add: 'personal.health:add',
      edit: 'personal.health:edit',
      delete: 'personal.health:delete',
    },
    /** 收入状况 */
    finance: {
      read: 'personal.finance:read',
      add: 'personal.finance:add',
      edit: 'personal.finance:edit',
      delete: 'personal.finance:delete',
    },
    /** 家庭 */
    family: {
      read: 'personal.family:read',
      add: 'personal.family:add',
      edit: 'personal.family:edit',
      delete: 'personal.family:delete',
    },
    /** 社交 */
    social: {
      read: 'personal.social:read',
      add: 'personal.social:add',
      edit: 'personal.social:edit',
      delete: 'personal.social:delete',
    },
  },
} as const;
