import ts from "typescript";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sourcePath = path.resolve(
  __dirname,
  "../packages/core/src/constants/permissions.ts"
);
const targetPath = path.resolve(
  __dirname,
  "../../platform/packages/ui/src/hooks/usePermission.ts"
);

const fileContent = fs.readFileSync(sourcePath, "utf-8");
const sourceFile = ts.createSourceFile(
  "permissions.ts",
  fileContent,
  ts.ScriptTarget.Latest,
  true
);

let permissionSeedsNode: ts.ObjectLiteralExpression | null = null;

function visit(node: ts.Node) {
  if (
    ts.isVariableDeclaration(node) &&
    ts.isIdentifier(node.name) &&
    node.name.text === "permissionSeeds"
  ) {
    let initializer = node.initializer;
    while (
      initializer &&
      (ts.isAsExpression(initializer) || ts.isSatisfiesExpression(initializer))
    ) {
      initializer = initializer.expression;
    }
    if (initializer && ts.isObjectLiteralExpression(initializer)) {
      permissionSeedsNode = initializer;
    }
  }
  ts.forEachChild(node, visit);
}

visit(sourceFile);

if (!permissionSeedsNode) {
  console.error("Could not find permissionSeeds in permissions.ts");
  process.exit(1);
}

function getJSDocComment(node: ts.Node): string | undefined {
  const sourceText = sourceFile.getFullText();
  const ranges = ts.getLeadingCommentRanges(sourceText, node.pos);
  if (ranges && ranges.length > 0) {
    const commentRange = ranges[ranges.length - 1];
    const commentText = sourceText.slice(commentRange.pos, commentRange.end);
    return commentText
      .replace(/\/\*\*+\s*/, "")
      .replace(/\s\*+\/\s*/, "")
      .replace(/^\s*\*\s*/gm, "")
      .trim();
  }
  return undefined;
}

const formatKey = (key: string) => key.replace(/[-_.]/g, "_").toLowerCase();

let content = `// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量
`;

function renderModuleBody(
  modulesObj: ts.Expression,
  parentKey: string,
  indent: string
): string {
  let res = "{\n";
  if (ts.isObjectLiteralExpression(modulesObj)) {
    // 1. Output parent-level actions (module is "")
    const parentActionsProp = modulesObj.properties.find((p) => {
      if (!ts.isPropertyAssignment(p)) return false;
      const name = ts.isStringLiteral(p.name) ? p.name.text : "";
      return name === "";
    });

    if (parentActionsProp && ts.isPropertyAssignment(parentActionsProp)) {
      const actionsArr = parentActionsProp.initializer;
      if (ts.isArrayLiteralExpression(actionsArr)) {
        actionsArr.elements.forEach((el) => {
          if (ts.isStringLiteral(el)) {
            const action = el.text;
            const actionKey = formatKey(action);
            res += `${indent}  ${actionKey}: '${parentKey}:${action}',\n`;
          }
        });
      }
    }

    // 2. Output modules (with recursion support for nested objects)
    modulesObj.properties.forEach((subProp) => {
      if (!ts.isPropertyAssignment(subProp)) return;
      const name = ts.isStringLiteral(subProp.name)
        ? subProp.name.text
        : ts.isIdentifier(subProp.name)
          ? subProp.name.text
          : "";
      if (name === "") return;

      const constName = formatKey(name);
      const desc = getJSDocComment(subProp) || name;
      const init = subProp.initializer;

      res += `${indent}  /** ${desc} */\n`;
      if (ts.isArrayLiteralExpression(init)) {
        res += `${indent}  ${constName}: {\n`;
        init.elements.forEach((el) => {
          if (ts.isStringLiteral(el)) {
            const action = el.text;
            const actionKey = formatKey(action);
            res += `${indent}    ${actionKey}: '${parentKey}.${name}:${action}',\n`;
          }
        });
        res += `${indent}  },\n`;
      } else if (ts.isObjectLiteralExpression(init)) {
        res += `${indent}  ${constName}: ${renderModuleBody(
          init,
          `${parentKey}.${name}`,
          indent + "  "
        )},\n`;
      }
    });
  }
  res += `${indent}}`;
  return res;
}

const adminProperties: string[] = [];
const enterpriseProperties: string[] = [];
let personalBody = "";

// @ts-expect-error TS inference is poor here
permissionSeedsNode.properties.forEach((parentProp) => {
  if (!ts.isPropertyAssignment(parentProp)) return;

  const parentKey =
    ts.isIdentifier(parentProp.name) || ts.isStringLiteral(parentProp.name)
      ? parentProp.name.text
      : "";
  if (!parentKey) return;

  const desc = getJSDocComment(parentProp) || parentKey;
  const init = parentProp.initializer;

  if (parentKey === "personal") {
    personalBody = renderModuleBody(init, "personal", "  ");
    return;
  }

  // 统一处理 admin 和 enterprise 两个需要拆分/拼装的顶级组
  const isEnterprise =
    parentKey === "enterprise" ||
    parentKey === "organization" ||
    parentKey === "executive";
  const targetList = isEnterprise ? enterpriseProperties : adminProperties;
  const rootKey = isEnterprise ? "enterprise" : "admin";

  if (parentKey === rootKey) {
    // 自身级平铺 actions
    if (ts.isObjectLiteralExpression(init)) {
      const parentActionsProp = init.properties.find(
        (p) =>
          ts.isPropertyAssignment(p) &&
          (ts.isStringLiteral(p.name) ? p.name.text : "") === ""
      );
      if (
        parentActionsProp &&
        ts.isPropertyAssignment(parentActionsProp) &&
        ts.isArrayLiteralExpression(parentActionsProp.initializer)
      ) {
        parentActionsProp.initializer.elements.forEach((el) => {
          if (ts.isStringLiteral(el)) {
            const action = el.text;
            const actionKey = formatKey(action);
            targetList.push(`    ${actionKey}: '${rootKey}:${action}',`);
          }
        });
      }
    }
  } else {
    // 子模块嵌套
    const subKey = parentKey.startsWith("admin.")
      ? parentKey.slice(6)
      : parentKey;
    const subKeyConst = formatKey(subKey);
    const bodyStr = renderModuleBody(init, parentKey, "    ");
    targetList.push(`    /** ${desc} */\n    ${subKeyConst}: ${bodyStr},`);
  }
});

// Output main permissions structure
content += `\nexport const permissions = {\n`;
content += `  admin: {\n${adminProperties.join("\n")}\n  },\n`;
content += `  enterprise: {\n${enterpriseProperties.join("\n")}\n  },\n`;
content += `  personal: ${personalBody},\n`;
content += `} as const;\n`;

// Ensure the directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, content, "utf-8");
console.log(
  "Permissions successfully synced (AST-based) and written to:",
  targetPath
);
