import ts from "typescript";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const sourcePath = path.resolve(__dirname, "../src/constants/permissions.ts");
const targetPath = path.resolve(
  __dirname,
  "../../platform/src/hooks/usePermission.ts"
);

const fileContent = fs.readFileSync(sourcePath, "utf-8");
const sourceFile = ts.createSourceFile(
  "permissions.ts",
  fileContent,
  ts.ScriptTarget.Latest,
  true
);

let permissionSeedsNode: ts.ObjectLiteralExpression | null = null;

function visit(node: ts.Node) {
  if (
    ts.isVariableDeclaration(node) &&
    ts.isIdentifier(node.name) &&
    node.name.text === "permissionSeeds"
  ) {
    let initializer = node.initializer;
    while (
      initializer &&
      (ts.isAsExpression(initializer) || ts.isSatisfiesExpression(initializer))
    ) {
      initializer = initializer.expression;
    }
    if (initializer && ts.isObjectLiteralExpression(initializer)) {
      permissionSeedsNode = initializer;
    }
  }
  ts.forEachChild(node, visit);
}

visit(sourceFile);

if (!permissionSeedsNode) {
  console.error("Could not find permissionSeeds in permissions.ts");
  process.exit(1);
}

function getJSDocComment(node: ts.Node): string | undefined {
  const sourceText = sourceFile.getFullText();
  const ranges = ts.getLeadingCommentRanges(sourceText, node.pos);
  if (ranges && ranges.length > 0) {
    const commentRange = ranges[ranges.length - 1];
    const commentText = sourceText.slice(commentRange.pos, commentRange.end);
    return commentText
      .replace(/\/\*\*+\s*/, "")
      .replace(/\s*\*+\/\s*/, "")
      .replace(/^\s*\*\s*/gm, "")
      .trim();
  }
  return undefined;
}

const formatKey = (key: string) => key.replace(/[-_]/g, "_").toUpperCase();

let content = `// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量
`;

permissionSeedsNode.properties.forEach((parentProp) => {
  if (!ts.isPropertyAssignment(parentProp) || !ts.isIdentifier(parentProp.name))
    return;

  const parentKey = parentProp.name.text;
  const parentConstName = formatKey(parentKey);
  const parentDesc = getJSDocComment(parentProp) || parentKey;

  content += `\n/** ${parentDesc} */\nexport const ${parentConstName} = {\n`;

  const modulesObj = parentProp.initializer;
  if (ts.isObjectLiteralExpression(modulesObj)) {
    // 1. Output parent-level actions (module is "")
    const parentActionsProp = modulesObj.properties.find((p) => {
      if (!ts.isPropertyAssignment(p)) return false;
      const name = ts.isStringLiteral(p.name) ? p.name.text : "";
      return name === "";
    });

    if (parentActionsProp && ts.isPropertyAssignment(parentActionsProp)) {
      const actionsArr = parentActionsProp.initializer;
      if (ts.isArrayLiteralExpression(actionsArr)) {
        actionsArr.elements.forEach((el) => {
          if (ts.isStringLiteral(el)) {
            const action = el.text;
            const actionKey = formatKey(action);
            content += `  ${actionKey}: '${parentKey}:${action}',\n`;
          }
        });
      }
    }

    // 2. Output modules
    modulesObj.properties.forEach((moduleProp) => {
      if (!ts.isPropertyAssignment(moduleProp)) return;
      let moduleKey = "";
      if (ts.isIdentifier(moduleProp.name)) {
        moduleKey = moduleProp.name.text;
      } else if (ts.isStringLiteral(moduleProp.name)) {
        moduleKey = moduleProp.name.text;
      }

      if (moduleKey === "") return;

      const moduleConstName = formatKey(moduleKey);
      const moduleDesc = getJSDocComment(moduleProp) || moduleKey;

      content += `  /** ${moduleDesc} */\n`;
      content += `  ${moduleConstName}: {\n`;

      const actionsArr = moduleProp.initializer;
      if (ts.isArrayLiteralExpression(actionsArr)) {
        actionsArr.elements.forEach((el) => {
          if (ts.isStringLiteral(el)) {
            const action = el.text;
            const actionKey = formatKey(action);
            content += `    ${actionKey}: '${parentKey}.${moduleKey}:${action}',\n`;
          }
        });
      }
      content += `  },\n`;
    });
  }

  content += `} as const;\n`;
});

// Ensure the directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, content, "utf-8");
console.log(
  "Permissions successfully synced (AST-based) and written to:",
  targetPath
);
