import { permissionSeeds } from "../src/constants/permissions";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetPath = path.resolve(
  __dirname,
  "../../platform/src/hooks/usePermission.ts"
);

const formatKey = (key: string) => key.replace(/[-_]/g, "_").toUpperCase();

const DESC_MAP: Record<string, string> = {
  system: "系统管理",
  "system.user": "用户管理",
  "system.role": "角色管理",
  "system.permission": "权限管理",
  "system.department": "部门管理",
  "system.menu": "菜单管理",
  "system.role_permission": "角色权限管理",
  "system.auth": "个人信息",
  "system.schema_form": "动态表单配置",
  "system.schema_form_data": "动态表单数据",
  mail: "邮件",
  "mail.account": "邮件账户",
  "mail.template": "邮件模板",
  "mail.log": "邮件日志",
  i18n: "国际化",
  "i18n.language": "语言管理",
  "i18n.region": "地区管理",
  "i18n.translation": "翻译管理",
  maintenance: "运维",
  "maintenance.cache": "缓存管理",
  "maintenance.audit_login": "登录日志",
  "maintenance.cron": "定时任务管理",
  "maintenance.api_task": "API 采集任务管理",
  "maintenance.api_docs": "API 文档管理",
  oss: "存储",
  "oss.config": "存储配置",
  "oss.file": "文件管理",
  enterprise: "企业",
  "enterprise.attendance": "考勤管理",
  ai: "AI",
  "ai.config": "AI 配置",
  "ai.chat": "AI 对话",
  swarm: "Swarm 集群",
  "swarm.docker": "Swarm 集群 Docker 服务管理",
  "swarm.nodes": "Swarm 节点管理",
  "swarm.docker_config": "Swarm Docker配置管理",
};

const getDescription = (parent: string, module?: string) => {
  const key = module ? `${parent}.${module}` : parent;
  return DESC_MAP[key] || key;
};

let content = `// This file is auto-generated by server/scripts/sync-permissions.ts.
// Do not edit this file manually.

import { useContext } from 'react';
import { PermissionContext } from '@/contexts/PermissionContext';

/** 权限控制 Hook */
export const usePermission = () => {
  const context = useContext(PermissionContext);
  if (!context) {
    throw new Error('usePermission must be used within a PermissionProvider');
  }
  return context;
};

// 权限码常量
`;

for (const [parent, modules] of Object.entries(permissionSeeds)) {
  const parentConstName = formatKey(parent);
  const parentDesc = getDescription(parent);
  content += `\n/** ${parentDesc} */\nexport const ${parentConstName} = {\n`;

  // 1. Output parent-level actions (module is "")
  if (modules[""]) {
    for (const action of modules[""]) {
      const actionKey = formatKey(action);
      content += `  ${actionKey}: '${parent}:${action}',\n`;
    }
  }

  // 2. Output modules
  for (const [module, actions] of Object.entries(modules)) {
    if (module === "") continue;
    const moduleConstName = formatKey(module);
    const moduleDesc = getDescription(parent, module);
    content += `  /** ${moduleDesc} */\n`;
    content += `  ${moduleConstName}: {\n`;
    for (const action of actions) {
      const actionKey = formatKey(action);
      content += `    ${actionKey}: '${parent}.${module}:${action}',\n`;
    }
    content += `  },\n`;
  }

  content += `} as const;\n`;
}

// Ensure the directory exists
const dir = path.dirname(targetPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(targetPath, content, "utf-8");
console.log("Permissions successfully synced and written to:", targetPath);
