/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/mail/account/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加 mailAccount
         * @description 添加 mailAccount
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountAddReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountAddRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/account/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailAccount
         * @description 查询 mailAccount
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询 mailAccount */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountGetReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountGetRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/account/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailAccount列表
         * @description 查询 mailAccount列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountListReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountListRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/account/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 更新 mailAccount
         * @description 更新 mailAccount
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountUpdateReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountUpdateRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/account/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除 mailAccount
         * @description 删除 mailAccount
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountDeleteReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountDeleteRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/account/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 验证 mailAccount 配置
         * @description 验证 mailAccount 配置
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 验证 mailAccount */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailAccountVerifyReq"];
                };
            };
            responses: {
                /** @description 验证成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailAccountVerifyRes"];
                    };
                };
                /** @description 验证失败 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/log/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加 mailLog
         * @description 添加 mailLog
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailLogAddReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailLogAddRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/log/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailLog
         * @description 查询 mailLog
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询 mailLog */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailLogGetReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailLogGetRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/log/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailLog列表
         * @description 查询 mailLog列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailLogListReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailLogListRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/log/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 更新 mailLog
         * @description 更新 mailLog
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailLogUpdateReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailLogUpdateRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/log/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除 mailLog
         * @description 删除 mailLog
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailLogDeleteReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailLogDeleteRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/send/single": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 单个 mailSend
         * @description 单个 mailSend
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailSendSingleReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailSendSingleRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/template/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加 mailTemplate
         * @description 添加 mailTemplate
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailTemplateAddReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailTemplateAddRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/template/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailTemplate
         * @description 查询 mailTemplate
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询 mailTemplate */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailTemplateGetReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailTemplateGetRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/template/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询 mailTemplate列表
         * @description 查询 mailTemplate列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailTemplateListReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailTemplateListRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/template/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 更新 mailTemplate
         * @description 更新 mailTemplate
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailTemplateUpdateReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailTemplateUpdateRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mail/template/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除 mailTemplate
         * @description 删除 mailTemplate
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["mailTemplateDeleteReq"];
                };
            };
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["mailTemplateDeleteRes"];
                    };
                };
                /** @description 校验失败 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorInvalidRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorInvalidRequest: {
            ok: boolean;
            message: string;
            errors?: {
                instanceLocation?: string;
                keyword?: string;
                keywordLocation?: string;
                error?: string;
            }[];
        };
        mailAccountAddReq: {
            /**
             * Format: email
             * @description 邮箱地址
             * @example maddison53@ethereal.email
             */
            mailAddress: string;
            /**
             * @description 邮箱密码
             * @example jn7jnAPss4f63QBp6D
             */
            password: string;
            /**
             * @description 昵称
             * @example Maddison Foo KochZh
             */
            nickname: string;
            /**
             * @description 邮箱服务器地址
             * @example smtp.ethereal.email
             */
            host?: string;
            /**
             * @description 邮箱服务器端口
             * @default 587
             */
            port: number;
            /**
             * @description 是否启用SSL
             * @default true
             */
            sslEnable: boolean;
            /**
             * @description 是否启用STARTTLS
             * @default false
             */
            starttlsEnable: boolean;
            /** @description 邮箱账号拥有者 */
            accountOwner: string;
        };
        mailAccountAddRes: {
            ok: boolean;
            /**
             * @description 邮箱账号id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailAccountGetReq: {
            /**
             * @description 邮箱账号id
             * @example 1
             */
            id?: number;
            /**
             * Format: email
             * @description 邮箱地址
             * @example maddison53@ethereal.email
             */
            mailAddress?: string;
        } & (unknown | unknown);
        mailAccountGetRes: {
            ok: boolean;
            data: {
                /**
                 * @description 邮箱账号id
                 * @example 1
                 */
                id?: number;
                /**
                 * Format: email
                 * @description 邮箱地址
                 * @example maddison53@ethereal.email
                 */
                mailAddress?: string;
                /**
                 * @description 邮箱密码
                 * @example jn7jnAPss4f63QBp6D
                 */
                password?: string;
                /**
                 * @description 昵称
                 * @example Maddison Foo KochZh
                 */
                nickname?: string;
                /**
                 * @description 邮箱服务器地址
                 * @example smtp.ethereal.email
                 */
                host?: string;
                /**
                 * @description 邮箱服务器端口
                 * @default 587
                 */
                port: number;
                /**
                 * @description 是否启用SSL
                 * @default true
                 */
                sslEnable: boolean;
                /**
                 * @description 是否启用STARTTLS
                 * @default false
                 */
                starttlsEnable: boolean;
                /** @description 邮箱账号拥有者 */
                accountOwner?: string;
                /**
                 * @description 创建时间
                 * @example 1672531199000
                 */
                createTimeUtc?: number;
                /**
                 * @description 更新时间
                 * @example 1672531199000
                 */
                updateTimeUtc?: number | null;
            };
            message?: string;
        };
        mailAccountListReq: {
            /** @enum {string} */
            orderBy?: "id" | "accountOwner" | "createTimeUtc";
            descend?: boolean;
            /** @default 1 */
            pageNo: number;
            /** @default 10 */
            pageSize: number;
            /** @example  */
            keyword?: string;
        };
        mailAccountListRes: {
            ok: boolean;
            data: {
                list: {
                    /**
                     * @description 邮箱账号id
                     * @example 1
                     */
                    id?: number;
                    /**
                     * Format: email
                     * @description 邮箱地址
                     * @example maddison53@ethereal.email
                     */
                    mailAddress?: string;
                    /**
                     * @description 邮箱密码
                     * @example jn7jnAPss4f63QBp6D
                     */
                    password?: string;
                    /**
                     * @description 昵称
                     * @example Maddison Foo KochZh
                     */
                    nickname?: string;
                    /**
                     * @description 邮箱服务器地址
                     * @example smtp.ethereal.email
                     */
                    host?: string;
                    /**
                     * @description 邮箱服务器端口
                     * @default 587
                     */
                    port: number;
                    /**
                     * @description 是否启用SSL
                     * @default true
                     */
                    sslEnable: boolean;
                    /**
                     * @description 是否启用STARTTLS
                     * @default false
                     */
                    starttlsEnable: boolean;
                    /** @description 邮箱账号拥有者 */
                    accountOwner?: string;
                    /**
                     * @description 创建时间
                     * @example 1672531199000
                     */
                    createTimeUtc?: number;
                    /**
                     * @description 更新时间
                     * @example 1672531199000
                     */
                    updateTimeUtc?: number | null;
                }[];
                total?: number;
                currentPage?: number;
                totalPage?: number;
                pageNo?: number;
                pageSize?: number;
            };
            message?: string;
        };
        mailAccountUpdateReq: {
            /**
             * @description 邮箱账号id
             * @example 1
             */
            id: number;
            /**
             * Format: email
             * @description 邮箱地址
             * @example maddison53@ethereal.email
             */
            mailAddress?: string;
            /**
             * @description 邮箱密码
             * @example jn7jnAPss4f63QBp6D
             */
            password?: string;
            /**
             * @description 昵称
             * @example Maddison Foo KochZh
             */
            nickname?: string;
            /**
             * @description 邮箱服务器地址
             * @example smtp.ethereal.email
             */
            host?: string;
            /**
             * @description 邮箱服务器端口
             * @default 587
             */
            port: number;
            /**
             * @description 是否启用SSL
             * @default true
             */
            sslEnable: boolean;
            /**
             * @description 是否启用STARTTLS
             * @default false
             */
            starttlsEnable: boolean;
            /** @description 邮箱账号拥有者 */
            accountOwner?: string;
        };
        mailAccountUpdateRes: {
            ok: boolean;
            /**
             * @description 邮箱账号id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailAccountDeleteReq: {
            /**
             * @description 邮箱账号id
             * @example 1
             */
            id?: number;
            /**
             * Format: email
             * @description 邮箱地址
             * @example maddison53@ethereal.email
             */
            mailAddress?: string;
        } & (unknown | unknown);
        mailAccountDeleteRes: {
            ok: boolean;
            /**
             * @description 邮箱账号id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailAccountVerifyReq: {
            /**
             * @description 邮箱账号id
             * @example 1
             */
            id?: number;
            /**
             * Format: email
             * @description 邮箱地址
             * @example maddison53@ethereal.email
             */
            mailAddress?: string;
        } & (unknown | unknown);
        mailAccountVerifyRes: {
            ok: boolean;
            data: {
                /**
                 * @description 邮箱账号id
                 * @example 1
                 */
                id?: number;
                /**
                 * Format: email
                 * @description 邮箱地址
                 * @example maddison53@ethereal.email
                 */
                mailAddress?: string;
                /**
                 * @description 邮箱密码
                 * @example jn7jnAPss4f63QBp6D
                 */
                password?: string;
                /**
                 * @description 昵称
                 * @example Maddison Foo KochZh
                 */
                nickname?: string;
                /**
                 * @description 邮箱服务器地址
                 * @example smtp.ethereal.email
                 */
                host?: string;
                /**
                 * @description 邮箱服务器端口
                 * @default 587
                 */
                port: number;
                /**
                 * @description 是否启用SSL
                 * @default true
                 */
                sslEnable: boolean;
                /**
                 * @description 是否启用STARTTLS
                 * @default false
                 */
                starttlsEnable: boolean;
                /** @description 邮箱账号拥有者 */
                accountOwner?: string;
                /**
                 * @description 创建时间
                 * @example 1672531199000
                 */
                createTimeUtc?: number;
                /**
                 * @description 更新时间
                 * @example 1672531199000
                 */
                updateTimeUtc?: number | null;
            };
            message?: string;
        };
        mailLogAddReq: {
            /**
             * Format: email
             * @description 收件人邮箱地址
             * @example receiver@example.com
             */
            mailTo: string;
            /**
             * Format: email
             * @description 发件人邮箱地址
             * @example sender@example.com
             */
            mailFrom: string;
            /**
             * @description 邮件标题
             * @example Welcome to our service!
             */
            title: string;
            /** @description 邮件模板ID */
            templateId?: string;
            /** @description 邮件模板参数 */
            templateParams?: string;
            /** @description 发送状态 */
            sendStatus: boolean;
            /** @description 异常代码 */
            exceptionCode?: string;
            /** @description 异常详情 */
            exceptionDetails?: string;
        };
        mailLogAddRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailLogGetReq: {
            /**
             * @description index id
             * @example 1
             */
            id?: number;
        } & (unknown | unknown);
        mailLogGetRes: {
            ok: boolean;
            data: {
                /**
                 * @description index id
                 * @example 1
                 */
                id?: number;
                /**
                 * Format: email
                 * @description 收件人邮箱地址
                 * @example receiver@example.com
                 */
                mailTo?: string;
                /**
                 * Format: email
                 * @description 发件人邮箱地址
                 * @example sender@example.com
                 */
                mailFrom?: string;
                /**
                 * @description 邮件标题
                 * @example Welcome to our service!
                 */
                title?: string;
                /** @description 邮件模板ID */
                templateId?: string;
                /** @description 邮件模板参数 */
                templateParams?: string;
                /** @description 发送状态 */
                sendStatus?: boolean;
                /** @description 异常代码 */
                exceptionCode?: string;
                /** @description 异常详情 */
                exceptionDetails?: string;
                createTimeUtc?: number;
                updateTimeUtc?: number | null;
            };
            message?: string;
        };
        mailLogListReq: {
            /** @enum {string} */
            orderBy?: "id" | "mailTo" | "mailFrom" | "createTimeUtc";
            descend?: boolean;
            /** @default 1 */
            pageNo: number;
            /** @default 10 */
            pageSize: number;
            /** @example  */
            keyword?: string;
        };
        mailLogListRes: {
            ok: boolean;
            data: {
                list: {
                    /**
                     * @description index id
                     * @example 1
                     */
                    id?: number;
                    /**
                     * Format: email
                     * @description 收件人邮箱地址
                     * @example receiver@example.com
                     */
                    mailTo?: string;
                    /**
                     * Format: email
                     * @description 发件人邮箱地址
                     * @example sender@example.com
                     */
                    mailFrom?: string;
                    /**
                     * @description 邮件标题
                     * @example Welcome to our service!
                     */
                    title?: string;
                    /** @description 邮件模板ID */
                    templateId?: string;
                    /** @description 邮件模板参数 */
                    templateParams?: string;
                    /** @description 发送状态 */
                    sendStatus?: boolean;
                    /** @description 异常代码 */
                    exceptionCode?: string;
                    /** @description 异常详情 */
                    exceptionDetails?: string;
                    createTimeUtc?: number;
                    updateTimeUtc?: number | null;
                }[];
                total?: number;
                currentPage?: number;
                totalPage?: number;
                pageNo?: number;
                pageSize?: number;
            };
            message?: string;
        };
        mailLogUpdateReq: {
            /**
             * @description index id
             * @example 1
             */
            id: number;
            /**
             * Format: email
             * @description 收件人邮箱地址
             * @example receiver@example.com
             */
            mailTo?: string;
            /**
             * Format: email
             * @description 发件人邮箱地址
             * @example sender@example.com
             */
            mailFrom?: string;
            /**
             * @description 邮件标题
             * @example Welcome to our service!
             */
            title?: string;
            /** @description 邮件模板ID */
            templateId?: string;
            /** @description 邮件模板参数 */
            templateParams?: string;
            /** @description 发送状态 */
            sendStatus?: boolean;
            /** @description 异常代码 */
            exceptionCode?: string;
            /** @description 异常详情 */
            exceptionDetails?: string;
        };
        mailLogUpdateRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailLogDeleteReq: {
            /**
             * @description index id
             * @example 1
             */
            id?: number;
        } & (unknown | unknown);
        mailLogDeleteRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailSendSingleReq: {
            senderObj: {
                accountId?: number;
                mailAddress?: string;
            } & (unknown | unknown);
            receiverArr: {
                name: string;
                address: string;
            }[];
            contentObj: {
                templateId?: number;
                subject?: string;
                html?: string;
            };
        };
        mailSendSingleRes: {
            ok: boolean;
            data: {
                accepted: {
                    name: string;
                    address: string;
                }[];
                rejected: {
                    name: string;
                    address: string;
                }[];
            };
            message?: string;
        };
        mailTemplateAddReq: {
            /**
             * Format: email
             * @description 邮件模板名称
             * @example welcome_email
             */
            name: string;
            /**
             * @description 邮件标题
             * @example Welcome to our service!
             */
            title: string;
            /**
             * @description 语言代码
             * @example en-US
             */
            langCode?: string;
            /** @description 邮件内容 */
            content: string;
            /** @description 创建者名称 */
            creatorName: string;
            /** @description 邮件分类 */
            category?: string;
        };
        mailTemplateAddRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailTemplateGetReq: {
            /**
             * @description index id
             * @example 1
             */
            id?: number;
        } & (unknown | unknown);
        mailTemplateGetRes: {
            ok: boolean;
            data: {
                /**
                 * @description index id
                 * @example 1
                 */
                id?: number;
                /**
                 * Format: email
                 * @description 邮件模板名称
                 * @example welcome_email
                 */
                name?: string;
                /**
                 * @description 邮件标题
                 * @example Welcome to our service!
                 */
                title?: string;
                /**
                 * @description 语言代码
                 * @example en-US
                 */
                langCode?: string;
                /** @description 邮件内容 */
                content?: string;
                /** @description 创建者名称 */
                creatorName?: string;
                /** @description 邮件分类 */
                category?: string;
                createTimeUtc?: number;
                updateTimeUtc?: number | null;
            };
            message?: string;
        };
        mailTemplateListReq: {
            /** @enum {string} */
            orderBy?: "id" | "langCode" | "creatorName" | "category" | "createTimeUtc";
            descend?: boolean;
            /** @default 1 */
            pageNo: number;
            /** @default 10 */
            pageSize: number;
            /** @example  */
            keyword?: string;
        };
        mailTemplateListRes: {
            ok: boolean;
            data: {
                list: {
                    /**
                     * @description index id
                     * @example 1
                     */
                    id?: number;
                    /**
                     * Format: email
                     * @description 邮件模板名称
                     * @example welcome_email
                     */
                    name?: string;
                    /**
                     * @description 邮件标题
                     * @example Welcome to our service!
                     */
                    title?: string;
                    /**
                     * @description 语言代码
                     * @example en-US
                     */
                    langCode?: string;
                    /** @description 邮件内容 */
                    content?: string;
                    /** @description 创建者名称 */
                    creatorName?: string;
                    /** @description 邮件分类 */
                    category?: string;
                    createTimeUtc?: number;
                    updateTimeUtc?: number | null;
                }[];
                total?: number;
                currentPage?: number;
                totalPage?: number;
                pageNo?: number;
                pageSize?: number;
            };
            message?: string;
        };
        mailTemplateUpdateReq: {
            /**
             * @description index id
             * @example 1
             */
            id: number;
            /**
             * Format: email
             * @description 邮件模板名称
             * @example welcome_email
             */
            name?: string;
            /**
             * @description 邮件标题
             * @example Welcome to our service!
             */
            title?: string;
            /**
             * @description 语言代码
             * @example en-US
             */
            langCode?: string;
            /** @description 邮件内容 */
            content?: string;
            /** @description 创建者名称 */
            creatorName?: string;
            /** @description 邮件分类 */
            category?: string;
        };
        mailTemplateUpdateRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
        mailTemplateDeleteReq: {
            /**
             * @description index id
             * @example 1
             */
            id?: number;
        } & (unknown | unknown);
        mailTemplateDeleteRes: {
            ok: boolean;
            /**
             * @description index id
             * @example 1
             */
            data: number;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
